import InformationGuide, { informationGuideMetadata, type InformationGuideData } from "../_components/InformationGuide";

const data: InformationGuideData = {
  slug: "prokrastinering",
  title: "Prokrastinering – varför vi skjuter upp och hur du kommer igång | Relationsvarning",
  description: "Vad prokrastinering är, varför vi skjuter upp saker och praktiska sätt att komma igång när undvikande tar över.",
  h1: "Prokrastinering – varför skjuter vi upp saker?",
  eyebrow: "Vardag, fokus och igångsättning",
  intro: "Prokrastinering innebär att skjuta upp något man har tänkt eller behöver göra, trots att uppskjutandet kan få negativa följder. Det handlar ofta mindre om vilja och mer om vad som händer när uppgiften väcker obehag, osäkerhet eller motstånd.",
  datePublished: "2026-10-07T12:00:00+02:00", dateModified: "2026-10-07T12:00:00+02:00",
  sections: [
    { title: "Prokrastinering är inte samma sak som lathet", paragraphs: ["Att vila, välja bort något eller prioritera om kan vara genomtänkta beslut. Vid prokrastinering finns ofta en avsikt att göra uppgiften, men starten flyttas fram gång på gång.", "Mönstret kan bli självförstärkande: uppskjutandet ger en kort lättnad, medan uppgiften samtidigt växer i huvudet. Det säger inte att du är lat eller saknar ambition."] },
    { title: "Varför skjuter man upp saker?", paragraphs: ["En svår, tråkig eller otydlig uppgift kan väcka stress, rädsla för att misslyckas eller känslan av att inte veta var man ska börja. Då blir något enklare och mer direkt belönande lättare att välja i stunden."], bullets: ["Uppgiften känns för stor eller för vag.", "Kraven känns höga och det är svårt att acceptera ett första, ofullständigt försök.", "Energibrist, sömnbrist eller mycket annat som kräver uppmärksamhet gör starten tyngre.", "Distraktioner ger snabbare lättnad än uppgiften gör."] },
    { title: "Undvikande och känsloreglering", paragraphs: ["Prokrastinering kan fungera som ett sätt att tillfälligt komma undan en obehaglig känsla. Det kan vara oro, frustration, skam eller rädsla för att resultatet inte ska räcka till.", "Det betyder inte att känslan är fel. Ett mer hjälpsamt första steg kan vara att lägga märke till vad du försöker slippa just när du byter till något annat."] },
    { title: "Igångsättning och exekutiva funktioner", paragraphs: ["För vissa är hindret främst att överblicka, prioritera och ta första steget. Sådana förmågor brukar beskrivas som exekutiva funktioner. De påverkas av många saker och är inte ett tecken på en bestämd diagnos.", "När det främst är svårt att starta kan en mindre och tydligare startpunkt vara mer användbar än att försöka känna sig helt motiverad först."], links: [{ href: "/exekutiva-funktioner", label: "vad exekutiva funktioner är" }] },
    { title: "Prokrastinering och ADHD", paragraphs: ["Svårigheter med tid, organisation, fokus och igångsättning kan förekomma vid ADHD. Samtidigt är prokrastinering vanligt av många andra skäl. Att känna igen uppskjutande räcker därför inte för att säga vad det beror på.", "Om flera återkommande svårigheter med fokus, planering, impulsivitet och vardagspåverkan finns samtidigt kan ett självtest ge ett underlag för egen reflektion."] },
    { title: "Praktiska sätt att komma igång", paragraphs: ["Strategier fungerar bäst när de gör uppgiften konkret nog för just nästa steg. Målet är inte att skapa perfekt disciplin, utan att sänka tröskeln för att börja."], bullets: ["Bestäm en start som tar högst några minuter: öppna dokumentet, skriv rubriken eller ta fram materialet.", "Beskriv nästa handling i stället för hela projektet.", "Minska ett störmoment i taget, till exempel lägg mobilen utom räckhåll under en kort tidsperiod.", "Gör en enkel tidsram och utvärdera efteråt vad som hjälpte eller stod i vägen."] },
    { title: "När prokrastinering påverkar vardagen", paragraphs: ["När uppskjutandet återkommer och påverkar arbete, studier, ekonomi, relationer eller återhämtning kan det vara hjälpsamt att prata med vårdcentral, studenthälsa eller annan professionell kontakt. Du behöver inte först avgöra exakt vilken förklaring som stämmer."] },
  ],
  cta: { title: "Vill du förstå ett bredare mönster?", text: "Om du känner igen återkommande svårigheter med fokus, igångsättning och impulsivitet kan ADHD-testet vara en relevant nästa självreflektion. Det kan inte ställa diagnos.", href: "/adhd-test", label: "Läs om ADHD-testet" },
  related: [{ href: "/exekutiva-funktioner", label: "Exekutiva funktioner", description: "Om planering, arbetsminne och igångsättning." }, { href: "/adhd-symtom-vuxna", label: "ADHD-symtom hos vuxna", description: "Om återkommande mönster i vardagen." }, { href: "/audhd-test", label: "AuDHD-test för vuxna", description: "För självreflektion kring ADHD- och autismrelaterade områden." }, { href: "/standig-oro", label: "Ständig oro", description: "När tankar och sökandet efter lösningar fortsätter." }],
  faqs: [{ question: "Vad är prokrastinering?", answer: "Prokrastinering är att skjuta upp en avsedd uppgift trots att det kan skapa problem senare. Det kan handla om undvikande, otydliga steg, stress eller många andra faktorer." }, { question: "Är prokrastinering ett tecken på ADHD?", answer: "Nej. Prokrastinering förekommer av många skäl. ADHD kan vara en möjlig kontext när flera långvariga och återkommande svårigheter finns, men uppskjutande i sig säger inte vad orsaken är." }, { question: "Hur slutar man prokrastinera?", answer: "Börja med att göra nästa steg mindre och tydligare. Att minska distraktioner, avgränsa tiden och följa upp vad som stod i vägen kan vara mer hjälpsamt än att vänta på rätt känsla." }],
  sources: [{ href: "https://ki.se/forskning/popularvetenskap-och-dialog/medicinvetarna-en-podd-om-kis-forskning/medicinvetarna-17-skjuter-du-upp", label: "Karolinska Institutet – om prokrastinering och uppskjutarbeteende" }, { href: "https://www.lu.se/student/studentstod-och-halsa/studenthalsan/prokrastinering", label: "Lunds universitet – om prokrastinering" }],
};

export const metadata = informationGuideMetadata(data);
export default function Page() { return <InformationGuide data={data} />; }
