import type { Metadata } from "next";
import Link from "next/link";
import EditorialSurface from "../_components/EditorialSurface";
import { GuideSection, textLink } from "../_components/ContentGuide";
import { EditorialArticleJsonLd, getEditorialArticleSchema, getEditorialMetadata } from "../_seo/editorialSeo";

const title = "Högkänslig personlighet – tecken, egenskaper och HSP | Relationsvarning";
const description = "Vad innebär det att vara högkänslig? Läs om vanliga HSP-drag, överstimulering, känslor, styrkor och utmaningar – och gör HSP-testet om du vill utforska din egen profil.";
export const metadata: Metadata = { title, description, robots: { index: true, follow: true }, ...getEditorialMetadata({ route: "/hogkanslig-personlighet", title, description, datePublished: "2026-09-28T14:00:00+02:00", dateModified: "2026-09-28T14:00:00+02:00" }) };
const article = getEditorialArticleSchema({ route: "/hogkanslig-personlighet", title, description, datePublished: "2026-09-28T14:00:00+02:00", dateModified: "2026-09-28T14:00:00+02:00" });
const cta = "inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-[#9d5663] px-5 py-3 text-center font-semibold text-white transition hover:bg-[#844451] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#576f60] sm:w-auto";
const traits = ["Blir lätt överstimulerad av mycket ljud, människor eller aktivitet.", "Märker subtila detaljer i miljön eller i hur andra uttrycker sig.", "Påverkas av stämningar och sociala signaler.", "Bearbetar upplevelser och beslut grundligt.", "Reagerar starkt på känslomässiga händelser.", "Behöver ofta återhämtning efter intensiva dagar.", "Kan påverkas djupt av musik, natur, konst eller andra positiva upplevelser."] as const;
const faqs = [["Vad betyder HSP?", "HSP står för Highly Sensitive Person. Begreppet används om personer som upplever hög känslighet för olika typer av intryck och stimuli."], ["Är högkänslighet en diagnos?", "Nej. Högkänslighet är inte en medicinsk eller psykiatrisk diagnos."], ["Hur vet man om man är högkänslig?", "Det finns inget enskilt tecken som avgör det. Många tittar i stället på ett mönster av exempelvis överstimulering, sensorisk känslighet, djup bearbetning och starka reaktioner på känslor och intryck."], ["Kan man vara högkänslig utan att vara känslosam?", "Ja. Känslighet kan visa sig på olika sätt. En person kan exempelvis vara mycket känslig för ljud och miljöer utan att uppleva ovanligt stark emotionell reaktivitet."], ["Är högkänslighet samma sak som ADHD?", "Nej. Det finns vissa överlappande upplevelser, exempelvis överstimulering och känslighet för sinnesintryck, men ADHD är en neuropsykiatrisk diagnos medan HSP inte är det."]] as const;
const schema = [{ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Startsida", item: "https://www.relationsvarning.se/" }, { "@type": "ListItem", position: 2, name: "Artiklar", item: "https://www.relationsvarning.se/" }, { "@type": "ListItem", position: 3, name: "Högkänslig personlighet", item: "https://www.relationsvarning.se/hogkanslig-personlighet" }] }];

export default function SensitivePersonalityPage() {
  return <EditorialSurface><main data-rv="container" className="mx-auto max-w-4xl px-4 py-8 text-neutral-900 sm:px-6 sm:py-14"><EditorialArticleJsonLd data={article} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
    <nav aria-label="Brödsmulor" className="text-sm text-neutral-600"><Link href="/" className={textLink}>Relationsvarning</Link> / <span>Artiklar</span> / <span aria-current="page">Högkänslig personlighet</span></nav>
    <article><header className="mt-6 rounded-[28px] border border-[#e6d9d7] bg-[#fffaf8] px-5 py-8 shadow-sm sm:px-9 sm:py-12"><p className="text-sm font-semibold uppercase tracking-[.16em] text-[#9d5663]">HSP och högkänslighet</p><h1 className="mt-3">Högkänslig personlighet – vad innebär det?</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-neutral-700">En högkänslig person reagerar ofta starkare på intryck, känslor och subtila förändringar i omgivningen. Inom forskningen används begreppet <em>Sensory Processing Sensitivity</em>, SPS. Det är inte en diagnos utan ett sätt att beskriva individuella skillnader i känslighet och bearbetning av stimuli.</p><div className="mt-6 border-l-2 border-[#b8cbb8] pl-4"><p className="text-sm leading-6 text-neutral-700">Utforska din egen profil med vårt HSP-test.</p><Link data-rv="button" href="/hsp-test" className={`${cta} mt-3`}>Gör HSP-testet</Link></div></header>
      <GuideSection title="Vanliga drag hos en högkänslig person"><p>Hög känslighet ser olika ut mellan personer. Vanliga drag kan vara:</p><ul className="grid gap-3 sm:grid-cols-2">{traits.map((trait) => <li data-rv="card" key={trait} className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4 text-sm leading-6">{trait}</li>)}</ul></GuideSection>
      <GuideSection title="Varför blir vissa lätt överstimulerade?"><div className="max-w-3xl space-y-4"><p>När ljud, ljus, social aktivitet och krav kommer samtidigt kan det bli mentalt krävande. För en del går det åt mycket energi att sortera intrycken, särskilt i hektiska eller stökiga miljöer.</p><p>Behov av återhämtning betyder inte automatiskt att något är fel. Känslighet varierar mellan människor och kan också påverkas av stress, sömn och sammanhang. <Link href="/hsp-test" className={textLink}>Se hur känslig du är för överstimulering i vårt HSP-test</Link>.</p></div></GuideSection>
      <GuideSection title="Högkänslighet handlar inte bara om belastning"><div className="grid gap-3 sm:grid-cols-2"><div data-rv="card" className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5"><h3 className="font-semibold text-neutral-950">Möjliga styrkor</h3><p className="mt-2 text-sm leading-6">Detaljuppmärksamhet, djup reflektion, känslighet för nyanser och uppmärksamhet på sociala signaler kan hos vissa bidra till ett rikt sätt att uppleva vardagen.</p></div><div data-rv="card" className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5"><h3 className="font-semibold text-neutral-950">Positiva upplevelser</h3><p className="mt-2 text-sm leading-6">För vissa kan musik, natur, konst och små detaljer få stor betydelse. Det är inte en garanti för en viss egenskap, utan ett möjligt uttryck för känslighet.</p></div></div></GuideSection>
      <GuideSection title="När hög känslighet blir krävande"><p>Intensiva miljöer, många samtidiga krav och konfliktfyllda sociala situationer kan göra återhämtningen längre. En del fastnar också i analyser eller detaljer och har svårt att filtrera bort sådant som pågår runt omkring. Att förstå vilka situationer som tar energi kan vara ett första steg till bättre gränser och återhämtning.</p></GuideSection>
      <GuideSection title="Är HSP en diagnos?"><div className="max-w-3xl space-y-4"><p>Nej. HSP eller högkänslighet är inte en psykiatrisk eller medicinsk diagnos. Inom forskningen används bland annat begreppet Sensory Processing Sensitivity, SPS, för att beskriva individuella skillnader i hur människor reagerar på och bearbetar stimuli.</p><aside data-rv="callout" className="rounded-2xl border border-[#d8d5c8] bg-[#faf8f0] p-5 text-sm leading-6">Högkänslighet kan överlappa med upplevelser som även förekommer vid exempelvis ADHD, autism, stress och ångest. Liknande symtom betyder inte att tillstånden är samma sak.</aside><p><Link href="/hogkanslig-eller-adhd" className={textLink}>Läs om skillnaden mellan högkänslighet och ADHD</Link>.</p></div></GuideSection>
      <GuideSection title="Vill du se hur din egen känslighetsprofil ser ut?"><p>Vårt HSP-test innehåller 30 frågor och tittar på sex olika områden, bland annat överstimulering, sensorisk känslighet, emotionell reaktivitet och djup bearbetning.</p><Link data-rv="button" href="/hsp-test" className={cta}>Gör HSP-testet</Link><p className="text-sm font-semibold text-neutral-700">30 frågor · cirka 5 minuter · resultat direkt</p></GuideSection>
      <GuideSection title="Vanliga frågor om högkänslig personlighet"><div className="divide-y divide-neutral-200 border-y border-neutral-200">{faqs.map(([question, answer]) => <div key={question} className="py-5"><h3 className="font-semibold text-neutral-950">{question}</h3><p className="mt-2 text-sm leading-6">{answer}</p></div>)}</div></GuideSection>
    </article>
  </main></EditorialSurface>;
}
