import InformationGuide, { informationGuideMetadata, type InformationGuideData } from "../_components/InformationGuide";

const data: InformationGuideData = {
  slug: "exekutiva-funktioner",
  title: "Exekutiva funktioner – planering, arbetsminne och självreglering | Relationsvarning",
  description: "Vad exekutiva funktioner är och hur planering, arbetsminne, igångsättning, flexibilitet och självreglering kan märkas i vardagen.",
  h1: "Vad är exekutiva funktioner?",
  eyebrow: "Kognition och vardagsfungerande",
  intro: "Exekutiva funktioner är samlingsnamnet för mentala förmågor som hjälper oss att planera, komma igång, hålla riktning, anpassa oss och avsluta det vi gör. De behövs i många vanliga situationer och varierar med bland annat krav, stress, sömn och miljö.",
  datePublished: "2026-10-07T12:00:00+02:00", dateModified: "2026-10-07T12:00:00+02:00",
  sections: [
    { title: "Ett brett begrepp, inte en diagnos", paragraphs: ["Exekutiva funktioner beskriver hur man samordnar handlingar mot ett mål. De är inte en diagnos och enstaka svårigheter betyder inte att en viss diagnos förklarar dem.", "En person kan fungera bra i en tydlig situation men få det svårt när många steg, avbrott eller beslut ska hållas ihop samtidigt."] },
    { title: "Planering och prioritering", paragraphs: ["Planering handlar om att se vilka steg som behövs och i vilken ordning de är rimliga. Prioritering handlar om att välja vad som är viktigast just nu, även när flera saker känns brådskande."] },
    { title: "Arbetsminne", paragraphs: ["Arbetsminnet hjälper till att hålla information aktiv medan man använder den. Det kan märkas när man försöker följa instruktioner i flera led, komma ihåg varför man gick in i ett rum eller fortsätta efter ett avbrott."] },
    { title: "Igångsättning och att avsluta", paragraphs: ["Att veta vad man ska göra är inte alltid samma sak som att kunna börja. Igångsättning handlar om att översätta en avsikt till en konkret handling. Att avsluta kan på samma sätt bli svårt när detaljer, nya idéer eller osäkerhet tar över."], links: [{ href: "/prokrastinering", label: "prokrastinering och uppskjutande" }] },
    { title: "Impulskontroll, växling och flexibilitet", paragraphs: ["Impulskontroll kan hjälpa till att stanna upp innan man agerar. Flexibilitet handlar om att kunna byta strategi när förutsättningarna ändras. Båda förmågorna kan bli mer ansträngande vid stress, tidspress eller många samtidiga intryck."] },
    { title: "Självreglering i vardagen", paragraphs: ["Självreglering kan handla om att lägga märke till energi, känslor, tid och belastning så att man kan justera sitt nästa steg. Det är en förmåga som ofta underlättas av tydliga yttre strukturer, inte bara av att försöka mer."] },
    { title: "Exekutiva svårigheter vid ADHD och AuDHD", paragraphs: ["Planering, fokus, igångsättning och tidsuppfattning kan vara viktiga områden vid ADHD. Vid AuDHD kan sådana svårigheter finnas tillsammans med andra behov, till exempel kring rutiner, återhämtning eller sensoriska intryck.", "Liknande svårigheter kan också uppstå i andra situationer. Därför behöver en professionell bedömning alltid se till hela vardagen och fler möjliga förklaringar."] },
    { title: "Strategier och stöd", paragraphs: ["Ett stöd fungerar ofta bättre när det flyttar ut en del av kraven från huvudet till omgivningen."], bullets: ["Gör uppgiften synlig i en kort lista med ett nästa steg i taget.", "Använd påminnelser, kalender eller timer för sådant som annars behöver hållas i minnet.", "Planera övergångar och pauser, inte bara själva uppgiften.", "Be om tydliga instruktioner eller dela upp större uppgifter tillsammans med någon annan när det behövs."] },
  ],
  cta: { title: "Utforska dina egna vardagsmönster", text: "Om du känner igen bredare och återkommande svårigheter med fokus, organisation, igångsättning eller impulsivitet kan ett självtest hjälpa dig strukturera dina observationer. Det ersätter inte en professionell bedömning.", href: "/adhd-test", label: "Läs om ADHD-testet" },
  related: [{ href: "/prokrastinering", label: "Prokrastinering", description: "Varför uppskjutande kan uppstå och vad som kan hjälpa." }, { href: "/adhd-symtom-vuxna", label: "ADHD-symtom hos vuxna", description: "Om fokus, organisation och vardagspåverkan." }, { href: "/audhd-test", label: "AuDHD-test för vuxna", description: "Om ADHD- och autismrelaterade områden tillsammans." }, { href: "/autism-symtom-vuxna", label: "Autismsymtom hos vuxna", description: "Om socialt samspel, flexibilitet och sensorik." }],
  faqs: [{ question: "Vad menas med exekutiva funktioner?", answer: "Det är ett samlingsnamn för förmågor som bland annat hjälper oss att initiera, planera, hålla information aktiv, reglera impulser och anpassa oss när något ändras." }, { question: "Är exekutiva svårigheter samma sak som ADHD?", answer: "Nej. De kan förekomma vid ADHD, men också i andra sammanhang. Enstaka svårigheter räcker inte för att avgöra vad de beror på." }, { question: "Kan man få stöd med exekutiva svårigheter?", answer: "Ja. Yttre struktur, påminnelser, tydliga delsteg och anpassningar kan hjälpa. Om svårigheterna påverkar vardagen mycket kan vårdcentral eller arbetsterapeut vara en väg till vidare stöd." }],
  sources: [{ href: "https://vardpersonal.1177.se/globalassets/nkk/nationell/media/dokument/kunskapsstod/vardforlopp/bilagor-vardforlopp/bilaga-b.-fortsatt-rehabilitering-1.pdf", label: "1177 för vårdpersonal – om exekutiva funktioner" }, { href: "https://www.1177.se/Halland/undersokning-behandling/hjalpmedel/hjalpmedel-for-kognition-och-kommunikation/hjalpmedel-for-kognitivt-stod/", label: "1177 – hjälpmedel för kognitivt stöd" }],
};

export const metadata = informationGuideMetadata(data);
export default function Page() { return <InformationGuide data={data} />; }
