import type { Metadata } from "next";
import Link from "next/link";
import { canonicalHost } from "../../content/behaviors";
import { ContentGuide, GuideLinks, GuideSection, SourceList, SupportNotice, textLink } from "../_components/ContentGuide";

export const metadata: Metadata = {
  title: "Ekonomiskt våld i relation – tecken, exempel och hjälp",
  description: "Förstå ekonomiskt våld: kontroll över pengar, konton, BankID, arbete och skulder. Läs om gemensam ekonomi, egna val och vägar till stöd.",
  alternates: { canonical: `${canonicalHost}/ekonomiskt-vald` },
};

export default function EconomicViolenceGuide() {
  return <ContentGuide title="Ekonomiskt våld i relation – tecken, exempel och hjälp" intro="Ekonomiskt våld kan handla om att begränsa en partners pengar, utnyttja personens ekonomi eller hindra möjligheten att försörja sig. Det är inte samma sak som att ett hushåll har ont om pengar. Frågan är hur tillgångar, beslut och beroende används i relationen." breadcrumbs={[{ href: "/beteenden", label: "Beteenden" }]}>
    <GuideSection title="När pengar blir ett sätt att styra"><p>Kontrollen kan vara tydlig, som att du inte får använda ditt konto. Den kan också vara svårare att sätta ord på: du har pengar på papperet men måste försvara varje inköp eller be om tillstånd att betala en resa. Det kan begränsa både vardagen och möjligheten att förändra relationen.</p><p>En ojämn inkomstfördelning är inte i sig ekonomiskt våld. Det viktiga är om upplägget går att förstå och påverka, och om du kan uttrycka behov utan att bli hotad eller förnedrad.</p></GuideSection>
    <GuideSection title="Tecken och konkreta exempel"><h3 className="text-xl font-semibold text-neutral-900">Pengar och inköp</h3><p>Partnern kan kräva att få hela din inkomst, hålla inne pengar eller bestämma vilka inköp som är tillåtna. Gemensamma besparingar blir något annat när bara en person får avgöra vad den andra behöver, medan de egna utgifterna aldrig ifrågasätts.</p><h3 className="text-xl font-semibold text-neutral-900">Bankkonton och BankID</h3><p>Det kan handla om press att lämna över kontotillgång, logga in eller godkänna något du inte vill. Hjälp med en betalning ska inte innebära att en annan person tar över din e-legitimation. BankID är personligt och säkerhetskoden ska inte lämnas ut.</p><h3 className="text-xl font-semibold text-neutral-900">Lån, skulder och utnyttjande</h3><p>Du kan pressas att stå för lån eller avtal som främst gynnar partnern, utan att få en tydlig bild av villkoren. Om du upptäcker något du inte känner igen behöver du få individuell hjälp; en artikel kan inte avgöra vilket ansvar du har för ett visst avtal.</p><h3 className="text-xl font-semibold text-neutral-900">Arbete och inkomst</h3><p>Återkommande bråk inför arbetspass, krav på att sluta jobba eller hinder för studier kan minska möjligheten till egen försörjning. Det kan börja som ett förslag om hur familjen ska få vardagen att fungera men bli ett upplägg som du inte längre får ompröva.</p></GuideSection>
    <GuideLinksSection />
    <GuideSection title="Gemensam ekonomi eller påtvingat beroende?"><p>Par kan välja helt olika sätt att fördela pengar. Gemensamma konton, separata konton eller att en person sköter betalningarna behöver inte vara problem. Ett hållbart upplägg bygger på begriplig information och verklig delaktighet.</p><ul className="list-disc space-y-3 pl-5"><li><strong>Budget:</strong> båda kan diskutera prioriteringar, i stället för att den ena ensidigt bestämmer vad den andra får köpa.</li><li><strong>Insyn:</strong> du kan förstå räkningar och åtaganden, i stället för att bli avvisad när du ställer frågor.</li><li><strong>Förändring:</strong> upplägget går att ompröva när arbete, hälsa eller behov ändras, utan hot om att du ska bli utan pengar.</li></ul><p>Att vara ekonomiskt beroende av någon kan göra det svårt att säga ifrån. Det är inte ett personligt misslyckande och betyder inte att du har samtyckt till all kontroll.</p></GuideSection>
    <GuideSection title="Om konton eller BankID kan vara utsatta"><p>Läs alltid vad du godkänner och avstå från att signera något du inte förstår. Om någon kan använda ditt BankID, kontakta banken via en officiell kontaktväg för hjälp med spärr och nästa steg. Låt inte partnern ensam förklara vad en okänd signering innebär.</p><p>Om du samtidigt är rädd för hot eller våld behöver du tänka på den fysiska säkerheten. Ta hjälp med hur du kan kontakta banken och stödverksamheter tryggt. Den här guiden ersätter inte bankens säkerhetsrutiner eller individuell juridisk rådgivning.</p></GuideSection>
    <GuideSection title="Första steg mot bättre överblick och stöd"><ol className="list-decimal space-y-3 pl-5"><li>Om det går säkert, samla en bild av inkomster, räkningar och åtaganden som berör dig. Du behöver inte ha en komplett dokumentation innan du ber om hjälp.</li><li>Kontakta kommunens budget- och skuldrådgivning om du behöver hjälp att sortera skulder och betalningar. Fråga banken om kontotillgång och transaktioner du inte känner igen.</li><li>Prata med socialtjänsten eller en stödverksamhet om kontrollen gör dig otrygg eller hindrar dig från att förändra situationen. Berätta också om det finns barn eller praktiska hinder.</li></ol></GuideSection>
    <SupportNotice />
    <GuideSection title="Ekonomin kan vara en del av ett större mönster"><p>Om pengar används tillsammans med hot, förnedring eller isolering kan du läsa om <Link href="/psykiskt-vald" className={textLink}>psykiskt våld</Link>. På <Link href="/psykiskt-vald/hjalp" className={textLink}>sidan om hjälp och stöd</Link> finns fler vägar vidare.</p><p>Du hittar fler konkreta situationer i <Link href="/beteenden" className={textLink}>beteendeöversikten</Link>. Du behöver inte avgöra om något är ett brott för att söka stöd kring det du upplever.</p></GuideSection>
    <SourceList ids={["economic", "bankid", "budget", "violence"]} />
  </ContentGuide>;
}

function GuideLinksSection() {
  return <GuideSection title="Känner du igen kontroll över din egen ekonomi?"><GuideLinks links={[{ href: "/beteenden/partner-kontrollerar-min-ekonomi", label: "Min partner kontrollerar min ekonomi – vardagsexempel och gränser" }]} /></GuideSection>;
}
