export const levelTexts = {
  "Svagt autismrelaterat mönster": "Dina svar bildar inte något särskilt tydligt autismrelaterat mönster i det här testet. Du kan fortfarande känna igen dig i enskilda drag, men de verkar inte samlas till ett starkt helhetsmönster över de områden testet mäter.",
  "Vissa autismrelaterade drag": "Dina svar innehåller vissa drag som kan förekomma vid autism, men helhetsbilden är relativt svag eller blandad. Enskilda egenskaper behöver inte bero på autism och kan också förekomma av många andra skäl.",
  "Måttligt autismrelaterat mönster": "Dina svar visar ett måttligt autismrelaterat mönster över flera av områdena testet mäter. Det betyder inte att du har autism, men vissa kombinationer i dina svar är tydligare än vad som syns vid ett svagt eller ospecifikt resultat.",
  "Tydligt autismrelaterat mönster": "Dina svar visar ett tydligt autismrelaterat mönster över flera områden. Det är fortfarande inte en diagnos, men kombinationen av dina svar är tillräckligt tydlig för att vara värd att förstå mer noggrant – särskilt om mönstren funnits länge och påverkar vardagen.",
  "Mycket tydligt autismrelaterat mönster": "Dina svar visar ett mycket tydligt autismrelaterat mönster inom flera av områdena som testet kartlägger. Resultatet kan inte avgöra om du har autism, men om samma mönster funnits under lång tid och påverkar vardagen kan en professionell bedömning vara relevant.",
} as const;
export const profileTexts = {
  "Social-kommunikativ profil": "Socialt samspel och social kommunikation ligger tydligt högre än de andra mönsterområdena. Dina svar handlar särskilt om aktiv tolkning, outtalade förväntningar och samtal. Det beskriver svarens tyngdpunkt, inte orsaken till den sociala ansträngningen.",
  "Förutsägbarhets-/sensorisk profil": "Behov av förutsägbarhet och sensorisk känslighet framträder tillsammans och tydligare än övriga områden. Förändringar och många intryck kan enligt dina svar kräva anpassning. Denna kombination räcker inte ensam för att avgöra om autism är förklaringen.",
  "Fokuserad/intensiv profil": "Fokuserade intressen och uppslukande fokus är särskilt framträdande tillsammans med minst ett annat förhöjt område. Att fördjupa sig kan vara meningsfullt; frågan är också hur växlingar och andra uppgifter fungerar. Starka intressen i sig betyder inte autism.",
  "Bred kombinerad profil": "Minst tre mönsterområden är tydligt förhöjda och ligger relativt nära varandra. Det är kombinationen som präglar dina svar, snarare än ett enda område. Läs den tillsammans med dina separata uppgifter om vardagspåverkan och tidigare erfarenheter.",
  "Svagt eller ospecifikt mönster": "Svaren uppfyller inte modellens regler för en mer avgränsad produktprofil. Det kan bero på ett lågt symptomindex eller på en ojämn fördelning. Ett enskilt område kan fortfarande ligga högt. Ospecifikt betyder inte att dina upplevelser saknar betydelse.",
} as const;
export const areaTexts = [
  { low: "Du beskriver relativt lite aktiv analys eller ansträngning i de sociala situationer frågorna tar upp.", middle: "Sociala situationer kräver ibland aktivt arbete enligt dina svar, men inte genomgående på hög nivå.", high: "Dina svar beskriver återkommande aktiv analys, osäkerhet kring sociala förväntningar eller stor mental ansträngning i samspel." },
  { low: "Indirekta budskap och samtalssignaler framstår inte som ett stort problemområde i dina svar.", middle: "Vissa indirekta budskap eller samtalssignaler kan vara svåra att tolka enligt din självskattning.", high: "Att tolka antydningar, bokstavliga uttryck och outtalade samtalssignaler framträder som återkommande svårigheter." },
  { low: "Du uppger relativt lite stress eller svårighet kring de förändringar och växlingar testet frågar om.", middle: "Förutsägbarhet underlättar ibland, och vissa förändringar kräver tid att hantera enligt dina svar.", high: "Tydliga planer, bestämda sätt att göra saker och tid att ställa om har stor betydelse i dina svar." },
  { low: "Sensoriska intryck beskrivs som relativt lite belastande inom de situationer testet omfattar.", middle: "Vissa intryck eller miljöer kan vara belastande, men känsligheten är inte genomgående hög i svaren.", high: "Ljud, andra sinnesintryck och intensiva miljöer framträder som belastande. Du beskriver även undvikande eller behov av återhämtning." },
  { low: "Du känner relativt sällan igen det starkt uppslukande och återkommande fokus som frågorna beskriver.", middle: "Du beskriver viss fördjupning och uppslukande uppmärksamhet, utan att det präglar alla svar i området.", high: "Fördjupning, återkommande intressen och svårighet att avbryta fokus framträder tydligt. Området beskriver både egenskaper och möjliga praktiska hinder." },
  { low: "Den sammanvägda uppgiften om påverkan, återhämtning, anpassning och långvarighet är relativt låg.", middle: "Du beskriver en blandad bild av vardagspåverkan, återhämtning, anpassning och erfarenheter över tid.", high: "Den samlade skattningen av påverkan, återhämtning, anpassning och långvarighet är hög. En hög summa betyder inte att alla dessa delar är lika tydliga." },
] as const;
