import type { Metadata } from "next";
import Link from "next/link";
import EditorialSurface from "../_components/EditorialSurface";
import { GuideSection, textLink } from "../_components/ContentGuide";
import { EditorialArticleJsonLd, getEditorialArticleSchema, getEditorialMetadata } from "../_seo/editorialSeo";
import LandingAnalytics from "./LandingAnalytics";

const title = "IQ-test gratis – 40 frågor om logik och kognitiv förmåga | Relationsvarning";
const description = "Gör ett IQ-test gratis med 40 frågor om mönster, logik, siffror, språk och spatial förmåga. Få ett IQ-estimat och se din tydligaste styrka direkt.";
export const metadata: Metadata = { title, description, robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large" } }, ...getEditorialMetadata({ route: "/iq-test", title, description, datePublished: "2026-10-01T12:00:00+02:00", dateModified: "2026-10-01T12:00:00+02:00" }) };
const article = getEditorialArticleSchema({ route: "/iq-test", title, description, datePublished: "2026-10-01T12:00:00+02:00", dateModified: "2026-10-01T12:00:00+02:00" });
const cta = "inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-[#2f6b4f] px-5 py-3 text-center font-semibold text-white transition hover:bg-[#285c44] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#2f6b4f] sm:w-auto";
const areas = [["Mönsterigenkänning", "Egna visuella matriser där regler kan handla om riktning, antal, rotation och former."], ["Logiskt resonemang", "Slutsatser, villkor och ordningsföljder där det gäller att skilja det säkra från det möjliga."], ["Numeriskt resonemang", "Talserier, proportioner och enkel matematisk logik utan fokus på allmänbildning."], ["Verbalt resonemang", "Analogier, kategorier och relationer mellan begrepp."], ["Spatial förmåga", "Rotation, spegling, riktning och hur former förhåller sig till varandra i rummet."]] as const;
const faqs = [["Är IQ-testet gratis?", "Ja. Efter 40 frågor får du ett orienterande IQ-estimat direkt. Den fullständiga analysen med fem områden är valfri."], ["Vad mäter IQ-testet?", "Testet samlar uppgifter inom mönsterigenkänning, logik, numeriskt och verbalt resonemang samt spatial förmåga. Det är en bredare ögonblicksbild än en enda typ av gåta."], ["Är resultatet ett officiellt IQ-resultat?", "Nej. Resultatet är ett orienterande IQ-estimat från Relationsvarnings egna uppgifter, inte ett normerat, officiellt eller kliniskt psykologtest."], ["Hur lång tid tar testet?", "De flesta kan göra de 40 frågorna på omkring 10–15 minuter. Det finns ingen tidspress i testet."], ["Sparas mina svar?", "Svar och svarstider sparas lokalt i din webbläsare så att du kan återvända till testet. De används inte i IQ-estimatet i denna version."]] as const;
const supplementalSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };

export default function IqLandingPage() {
  return <EditorialSurface><LandingAnalytics /><main data-rv="container" className="mx-auto max-w-4xl px-4 py-8 text-neutral-900 sm:px-6 sm:py-14"><EditorialArticleJsonLd data={article} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(supplementalSchema).replace(/</g, "\\u003c") }} />
    <nav aria-label="Brödsmulor" className="text-sm text-neutral-600"><Link href="/" className={textLink}>Relationsvarning</Link> / <span aria-current="page">IQ-test</span></nav>
    <article><header className="mt-6 rounded-[28px] border border-[#d5e3d8] bg-[#f5faf6] px-5 py-8 shadow-sm sm:px-9 sm:py-12"><p className="text-sm font-semibold uppercase tracking-[.16em] text-[#2f6b4f]">IQ-test på svenska</p><h1 className="mt-3 max-w-3xl">IQ-test gratis – 40 frågor om logik och kognitiv förmåga</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-neutral-700">Testa hur du löser visuella mönster, logiska problem, talserier, ordrelationer och spatiala uppgifter. Efter 40 frågor får du ett IQ-estimat direkt.</p><div className="mt-7"><Link data-rv="button" href="/iq-test/test" className={cta}>Starta IQ-testet</Link></div><p className="mt-3 text-sm font-semibold text-neutral-700">40 frågor · cirka 10–15 minuter · resultat direkt</p><p className="mt-4 max-w-2xl text-sm leading-6 text-neutral-600">Ingen registrering. Testet är ett modernt, eget kognitivt test – inte ett officiellt psykologtest.</p></header>
      <GuideSection title="Fem områden i samma test"><p>Ett bra kognitivt test behöver mer än en typ av fråga. Därför väger testet samman fem olika områden, med en blandad svårighetskurva.</p><div className="grid gap-3 sm:grid-cols-2">{areas.map(([heading, copy]) => <div data-rv="card" key={heading} className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5"><h3 className="font-semibold text-neutral-950">{heading}</h3><p className="mt-2 text-sm leading-6">{copy}</p></div>)}</div><Link data-rv="button" href="/iq-test/test" className={cta}>Gör IQ-testet</Link></GuideSection>
      <GuideSection title="Så fungerar IQ-testet"><div className="grid gap-3 sm:grid-cols-3">{[["1. Svara på 40 frågor", "Uppgifterna blir gradvis mer utmanande, men områdena är blandade genom testet."], ["2. Få ett IQ-estimat", "Din viktade prestation översätts till ett avrundat, orienterande estimat."], ["3. Välj om du vill fördjupa dig", "Den valfria analysen visar hur dina fem områden förhåller sig till varandra."]].map(([heading, copy]) => <div key={heading} className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5"><h3 className="font-semibold text-neutral-950">{heading}</h3><p className="mt-2 text-sm leading-6">{copy}</p></div>)}</div></GuideSection>
      <GuideSection title="Vad innebär IQ-estimatet?"><p>Ett IQ-estimat sammanfattar prestationen i just den här uppsättningen kognitiva uppgifter. Estimatet är avsiktligt avrundat för att inte ge sken av klinisk precision.</p><p>Det ger en ögonblicksbild av hur du löste testets uppgifter, men ersätter inte standardiserad psykologisk testning. Sömn, stress, språk, vana vid formatet och situationen kan påverka resultatet.</p></GuideSection>
      <GuideSection title="Vad får du gratis – och i den fullständiga analysen?"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-[#d5e3d8] bg-[#f5faf6] p-5"><h3 className="font-semibold text-neutral-950">Gratis direkt efter testet</h3><ul className="mt-3 space-y-2 text-sm leading-6"><li>• Ditt orienterande IQ-estimat</li><li>• Kort information om vad estimatet betyder</li><li>• Ingen registrering krävs</li></ul></div><div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5"><h3 className="font-semibold text-neutral-950">Fullständig analys · 79 kr</h3><ul className="mt-3 space-y-2 text-sm leading-6"><li>• Resultat för samtliga fem områden</li><li>• Styrkor, svagare områden och relativa skillnader</li><li>• En samlad kognitiv profil</li><li>• Fördjupad tolkning av testets uppgiftstyper</li></ul></div></div></GuideSection>
      <GuideSection title="Frågor och svar om IQ-testet"><div className="divide-y divide-neutral-200 border-y border-neutral-200">{faqs.map(([question, answer]) => <div key={question} className="py-5"><h3 className="font-semibold text-neutral-950">{question}</h3><p className="mt-2 max-w-3xl text-sm leading-6">{answer}</p></div>)}</div></GuideSection>
      <section data-rv="panel" className="mt-12 rounded-[28px] border border-[#d5e3d8] bg-[#f5faf6] px-5 py-8 text-center sm:px-9 sm:py-10"><h2 className="text-3xl font-semibold tracking-tight text-neutral-950">Redo att testa din kognitiva profil?</h2><p className="mx-auto mt-3 max-w-xl leading-7 text-neutral-700">40 egna uppgifter. Fem områden. Ett IQ-estimat och en första personlig insikt direkt.</p><div className="mt-6"><Link data-rv="button" href="/iq-test/test" className={cta}>Starta IQ-testet</Link></div></section>
    </article>
  </main></EditorialSurface>;
}
