import type { ClusterGuideData } from "../_components/SeoClusterGuide";

const common = [
  { href: "/audhd", label: "Vad är AuDHD?", description: "Informationshubben om samtidig ADHD och autism." },
  { href: "/audhd-test", label: "AuDHD-test för vuxna", description: "En självskattning med 48 frågor inom åtta områden." },
];

export const audhdGuides = {
  audhd: {
    slug: "audhd",
    eyebrow: "AuDHD · informationshub",
    title: "Vad är AuDHD? ADHD och autism samtidigt | Relationsvarning",
    description: "Vad betyder AuDHD? Läs om samtidig ADHD och autism, överlappande drag, olika behov och hur du kan orientera dig utan att försöka ställa diagnos på dig själv.",
    h1: "Vad är AuDHD? ADHD och autism samtidigt",
    intro: "AuDHD är ett informellt ord som vissa använder när ADHD och autism förekommer samtidigt. Det är inte en separat diagnos. Begreppet kan ändå hjälpa när man vill förstå varför olika behov, styrkor och svårigheter inte alltid passar in i en enda enkel beskrivning.",
    sections: [
      { heading: "Ett vardagsord, inte en diagnos", paragraphs: ["ADHD och autism är olika neuropsykiatriska tillstånd som kan förekomma samtidigt. En formell bedömning undersöker varje tillstånd var för sig och väger in utvecklingshistoria, vardagspåverkan och andra möjliga förklaringar.", "Att känna igen drag från båda områdena betyder inte i sig att någon har ADHD, autism eller båda. Stress, sömnproblem, ångest och livssituation kan också påverka fokus, energi, social ork och återhämtning."], links: [{ href: "/adhd-eller-autism", label: "ADHD eller autism?" }, { href: "/adhd-och-autism-samtidigt", label: "När båda kan finnas samtidigt" }] },
      { heading: "Varför kan kombinationen kännas motsägelsefull?", paragraphs: ["En person kan vilja ha tydliga rutiner och samtidigt ha svårt att få dem att fungera över tid. Någon annan kan söka stimulans men bli snabbt överbelastad av intryck. Sådana upplevelser är inte diagnostiska fynd, men de kan vara värda att beskriva konkret.", "I stället för att fråga vilken etikett som passar bäst kan det vara hjälpsamt att skilja på situationer: vad tar energi, vad underlättar, vad händer vid förändringar och hur påverkas arbete, studier, hem eller relationer?"], links: [{ href: "/audhd-symtom-vuxna", label: "AuDHD hos vuxna" }, { href: "/audhd-masking", label: "AuDHD och masking" }] },
      { heading: "En självskattning kan strukturera, inte avgöra", paragraphs: ["Ett test kan vara ett sätt att samla observationer från flera områden. Relationsvarnings AuDHD-test beskriver självskattade mönster inom ADHD- och autismrelaterade områden samt masking, friktion och vardagspåverkan.", "Resultatet är inte en diagnos, en sannolikhet eller en ersättning för vårdens bedömning. Om svårigheter begränsar vardagen kan du kontakta vårdcentralen och beskriva vad du märker över tid."], links: [{ href: "/adhd-test", label: "ADHD-test för vuxna" }, { href: "/autism-test", label: "autismtest för vuxna" }] },
    ],
    relatedTitle: "Fördjupa dig i AuDHD",
    related: [
      { href: "/audhd-test", label: "AuDHD-test", description: "48 frågor om två områden och hur de samspelar." },
      { href: "/adhd-eller-autism", label: "ADHD eller autism?", description: "Skillnader, överlapp och frågor som ger mer nyans." },
      { href: "/adhd-och-autism-samtidigt", label: "ADHD och autism samtidigt", description: "Hur kombinationen kan märkas utan att bli en checklista." },
      { href: "/audhd-kvinnor", label: "AuDHD hos kvinnor", description: "Om variation, anpassning och varför synlighet inte avgör allt." },
      { href: "/audhd-masking", label: "AuDHD och masking", description: "När strategier hjälper utåt men tar energi inåt." },
      { href: "/audhd-symtom-vuxna", label: "AuDHD hos vuxna", description: "Vanliga vardagsmönster att förstå i sitt sammanhang." },
      { href: "/adhd-test", label: "ADHD-test", description: "En separat självskattning av ADHD-relaterade områden." },
      { href: "/autism-test", label: "Autismtest", description: "En separat självskattning av autismrelaterade områden." },
    ],
    cta: { title: "Vill du undersöka din egen kombination?", text: "AuDHD-testet är en självskattning för vuxna med 48 frågor inom åtta områden. Det hjälper dig att strukturera dina svar, men kan inte ställa diagnos.", href: "/audhd-test", label: "Till AuDHD-testet" },
    faq: [{ question: "Är AuDHD en diagnos?", answer: "Nej. AuDHD är ett informellt begrepp för samtidig ADHD och autism, inte en separat diagnos." }, { question: "Kan ADHD och autism finnas samtidigt?", answer: "Ja. De är olika tillstånd som kan förekomma samtidigt, men ett webbtest kan inte avgöra diagnos." }],
  },
  "adhd-eller-autism": {
    slug: "adhd-eller-autism",
    eyebrow: "ADHD, autism och överlapp",
    title: "ADHD eller autism? Skillnader, likheter och överlapp | Relationsvarning",
    description: "ADHD eller autism? Läs om skillnader, likheter och överlapp kring fokus, rutiner, social ork, sensorik och vardagspåverkan utan att använda enskilda drag som diagnos.",
    h1: "ADHD eller autism? Skillnader, likheter och överlapp",
    intro: "Fokusproblem, social trötthet eller svårigheter när planer ändras har sällan en enda självklar förklaring. Här är en vägledning för att jämföra ADHD- och autismrelaterade mönster utan att göra vardagliga igenkänningar till en diagnos.",
    parent: { href: "/audhd", label: "Vad är AuDHD?" },
    sections: [
      { heading: "Liknande upplevelser kan ha olika sammanhang", paragraphs: ["Både ADHD och autism kan påverka återhämtning, planering och hur krävande sociala situationer känns. Men vad som ligger bakom en upplevelse kan se olika ut från situation till situation, och flera förklaringar kan finnas samtidigt.", "Det är mer användbart att fråga vad som händer före, under och efter en svår situation än att räkna igenkänningar. Är det otydliga instruktioner, många avbrott, sinnesintryck, tidsplanering eller något annat som gör störst skillnad?"], links: [{ href: "/adhd-symtom-vuxna", label: "ADHD-symtom hos vuxna" }, { href: "/autism-symtom-vuxna", label: "autismsymtom hos vuxna" }] },
      { heading: "Några skillnader att hålla öppna", paragraphs: ["ADHD-relaterade svårigheter kan ofta handla om uppmärksamhet, igångsättning, tidsuppfattning, impulsivitet eller rastlöshet. Autismrelaterade mönster kan handla om social kommunikation, behov av förutsägbarhet, fokuserade intressen och sensorisk bearbetning.", "Beskrivningarna överlappar delvis och gäller inte lika för alla. En person kan ha tydliga drag inom ett område men inte ett annat, och en professionell bedömning behöver alltid se till helheten."], bullets: ["Enskilda drag räcker inte för diagnos.", "Utvecklingshistoria och vardagspåverkan är viktiga i en bedömning.", "Stress, ångest och sömnbrist kan bidra till liknande svårigheter."] },
      { heading: "När frågan egentligen gäller båda", paragraphs: ["Om du återkommande känner igen både ADHD- och autismrelaterade områden kan du läsa om hur samtidig ADHD och autism kan märkas. Det ersätter inte en bedömning, men kan ge ett språk för sådant som annars ser motsägelsefullt ut."], links: [{ href: "/adhd-och-autism-samtidigt", label: "ADHD och autism samtidigt" }, { href: "/audhd-test", label: "test för både ADHD- och autismdrag" }] },
    ],
    related: [...common, { href: "/adhd-test", label: "ADHD-test", description: "Utforska ADHD-relaterade områden separat." }, { href: "/autism-test", label: "Autismtest", description: "Utforska autismrelaterade områden separat." }],
    cta: { title: "Vill du se flera områden tillsammans?", text: "AuDHD-testet samlar självskattade ADHD- och autismrelaterade drag utan att göra anspråk på att avgöra diagnos.", href: "/audhd-test", label: "Gör AuDHD-testet för vuxna" },
    faq: [{ question: "Kan man själv avgöra om det är ADHD eller autism?", answer: "Nej. Egen reflektion kan vara ett första steg, men diagnostik kräver en bred bedömning av bland annat utveckling, vardagspåverkan och andra möjliga förklaringar." }],
  },
  "adhd-och-autism-samtidigt": {
    slug: "adhd-och-autism-samtidigt",
    eyebrow: "Samtidig ADHD och autism",
    title: "ADHD och autism samtidigt – hur kan det märkas? | Relationsvarning",
    description: "Läs om hur ADHD och autism samtidigt kan märkas i vardagen: behov som krockar, överstimulering, struktur, igångsättning och återhämtning. Inte en diagnosguide.",
    h1: "ADHD och autism samtidigt – hur kan det märkas?",
    intro: "Samtidig ADHD och autism kan innebära att olika behov behöver förstås sida vid sida. Vissa beskriver mer stöd av struktur men också svårigheter att upprätthålla den. Andra känner både starkt stimulansbehov och snabb överbelastning.",
    parent: { href: "/audhd", label: "Vad är AuDHD?" },
    sections: [
      { heading: "När behov drar åt olika håll", paragraphs: ["En rutin kan lugna samtidigt som det kan vara svårt att komma igång, komma ihåg alla steg eller följa planen när något oväntat händer. En ny miljö kan kännas stimulerande och samtidigt vara överväldigande på grund av ljud, ljus eller många sociala intryck.", "Sådana kombinationer bevisar inte att någon har ADHD och autism. De kan ändå vara praktiska att kartlägga eftersom de säger något om vilket stöd, vilken återhämtning eller vilka anpassningar som gör vardagen mer hanterbar."], links: [{ href: "/audhd-symtom-vuxna", label: "vanliga AuDHD-mönster hos vuxna" }] },
      { heading: "Det synliga berättar inte allt", paragraphs: ["En person kan genomföra en aktivitet och ändå behöva mycket förberedelse före eller återhämtning efter. Andra märker kanske bara det som blev gjort, inte planeringen, kompensationen eller energin som krävdes.", "Masking och kompensation är inte bevis för autism eller samtidig ADHD och autism. De är möjliga erfarenheter som behöver sättas i sammanhang med resten av livet."], links: [{ href: "/audhd-masking", label: "AuDHD och masking" }, { href: "/audhd-kvinnor", label: "AuDHD hos kvinnor" }] },
      { heading: "Vad en utredning behöver fråga vidare om", paragraphs: ["En klinisk bedömning tittar på mönster över tid, hur vardagen påverkas i flera miljöer, utvecklingshistoria och andra tänkbara förklaringar. Den avgör inte saken genom en enda totalsiffra eller ett enskilt igenkänt exempel.", "Om du söker hjälp kan konkreta observationer vara mer användbara än att försöka formulera en färdig diagnos: vad blir svårt, hur länge har det funnits och vad hjälper?"], links: [{ href: "/adhd-test", label: "ADHD-test för vuxna" }, { href: "/autism-test", label: "autismtest för vuxna" }] },
    ],
    related: [...common, { href: "/adhd-eller-autism", label: "ADHD eller autism?", description: "Om skillnader, likheter och överlapp." }],
    cta: { title: "Strukturera dina egna observationer", text: "AuDHD-testet tar upp åtta områden, inklusive masking, friktion och vardagspåverkan. Det är ett reflektionsunderlag, inte diagnostik.", href: "/audhd-test", label: "Till AuDHD-testet" },
  },
  "audhd-kvinnor": {
    slug: "audhd-kvinnor",
    eyebrow: "AuDHD hos kvinnor",
    title: "AuDHD hos kvinnor – när ADHD och autism döljer varandra | Relationsvarning",
    description: "Läs om AuDHD hos kvinnor, variation i uttryck, social anpassning, inre belastning och varför en fungerande utsida inte kan användas för att utesluta svårigheter.",
    h1: "AuDHD hos kvinnor – när ADHD och autism döljer varandra",
    intro: "En kvinna kan se organiserad ut utifrån men använda mycket energi för att planera, minnas, tolka sociala situationer eller återhämta sig. Samtidigt finns ingen enda kvinnlig profil för ADHD, autism eller deras samtidiga förekomst.",
    parent: { href: "/audhd", label: "Vad är AuDHD?" },
    sections: [
      { heading: "Ingen mall passar alla kvinnor", paragraphs: ["Kön säger inte hur ADHD eller autism ska märkas. Vissa har tidigt synliga svårigheter, andra har lärt sig strategier som gör dem mindre synliga, och många känner inte igen sig i någon av de vanliga bilderna.", "En försiktig beskrivning fokuserar därför på konkreta vardagssituationer: vad som tar kraft, vilka krav som blir svåra och vad som hjälper. Personlighet, kultur, stöd och livssituation spelar också roll."], links: [{ href: "/adhd-kvinnor", label: "ADHD hos kvinnor" }, { href: "/autism-kvinnor", label: "autism hos kvinnor" }] },
      { heading: "När anpassning gör bilden mindre tydlig", paragraphs: ["Vissa förbereder samtal, gör detaljerade listor eller imiterar sociala beteenden för att klara vardagen. Strategier kan vara hjälpsamma och samtidigt innebära trötthet, oro eller mindre utrymme för återhämtning.", "Att anpassa sig är inte ett diagnostiskt tecken och är inte unikt för kvinnor. Det är snarare en fråga om vad strategierna kostar och om de räcker när kraven ökar."], links: [{ href: "/audhd-masking", label: "masking vid AuDHD" }, { href: "/maskering-autism", label: "maskering vid autism" }] },
      { heading: "Utredning handlar om helhet, inte om att passa en stereotyp", paragraphs: ["En bedömning kan väga in erfarenheter från barndom, vardagspåverkan, relationer, arbete och andra möjliga förklaringar. Att ha klarat mycket själv utesluter inte behov av stöd, och svårigheter behöver inte bevisas genom att någon annan har sett dem.", "Ett självtest kan vara ett sätt att sortera frågor inför ett samtal, men kan inte avgöra om ADHD, autism eller AuDHD är rätt förklaring."], links: [{ href: "/audhd", label: "Vad är AuDHD?" }] },
    ],
    related: [...common, { href: "/adhd-och-autism-samtidigt", label: "ADHD och autism samtidigt", description: "Om behov som kan överlappa eller krocka." }],
    cta: { title: "Reflektera över din egen vardag", text: "AuDHD-testet är en självskattning för vuxna. Det tittar på flera områden och beskriver svarsmönster utan att sätta diagnos.", href: "/audhd-test", label: "Till AuDHD-testet" },
  },
  "audhd-masking": {
    slug: "audhd-masking",
    eyebrow: "Masking och kompensation",
    title: "AuDHD och masking – när anpassningen döljer svårigheterna | Relationsvarning",
    description: "Vad kan masking betyda vid AuDHD? Läs om social anpassning, kompensation, energikostnad och varför strategier inte kan användas som bevis för en diagnos.",
    h1: "AuDHD och masking – när anpassningen döljer svårigheterna",
    intro: "Masking används ofta för att beskriva ett aktivt arbete med att anpassa uttryck, kommunikation eller vardagsstrategier. Det kan göra att omgivningen ser mindre av vad som är svårt, men masking i sig visar inte att någon har autism, ADHD eller AuDHD.",
    parent: { href: "/audhd", label: "Vad är AuDHD?" },
    sections: [
      { heading: "Strategier kan hjälpa och kosta samtidigt", paragraphs: ["Att skriva manus inför ett möte, öva svar eller bygga mycket detaljerade system kan underlätta en situation. Frågan är också vad som händer efteråt: går det att återhämta sig, blir systemen hållbara och finns det plats för oväntade krav?", "En metod som fungerar i en period kan bli otillräcklig när arbete, studier, omsorgsansvar eller social belastning ökar. Det betyder inte automatiskt att en viss diagnos förklarar förändringen."], links: [{ href: "/audhd-symtom-vuxna", label: "AuDHD hos vuxna" }] },
      { heading: "Masking är bredare än social imitation", paragraphs: ["Anpassning kan också handla om att kontrollera rastlöshet, dölja glömska, undvika miljöer med för många intryck eller lägga mycket tid på förberedelser. Olika människor använder olika strategier och har olika skäl till dem.", "Därför är det klokt att beskriva konkreta situationer i stället för att använda masking som ett bevis. Hur mycket energi tar strategin, när behövs den och vad händer när den inte räcker?"], links: [{ href: "/maskering-autism", label: "maskering vid autism" }, { href: "/adhd-och-autism-samtidigt", label: "ADHD och autism samtidigt" }] },
      { heading: "När är det rimligt att söka stöd?", paragraphs: ["Om anpassning, stress eller återhämtning begränsar vardagen kan ett samtal med vårdcentralen vara ett nästa steg. En professionell bedömning behöver ta hänsyn till hela situationen och till alternativa förklaringar.", "Du behöver inte ha en färdig teori om dig själv för att söka stöd. Observationer om belastning, återhämtning och situationer som blir svåra kan vara en bra utgångspunkt."], links: [{ href: "/audhd", label: "AuDHD-hubben" }] },
    ],
    related: [...common, { href: "/audhd-kvinnor", label: "AuDHD hos kvinnor", description: "Om variation och synlig respektive osynlig belastning." }],
    cta: { title: "Se strategier i ett större sammanhang", text: "AuDHD-testet håller masking separat från ADHD- och autismrelaterade index. Resultatet kan ge språk åt egna svar men är inte diagnostiskt.", href: "/audhd-test", label: "Gör AuDHD-testet för vuxna" },
  },
  "audhd-symtom-vuxna": {
    slug: "audhd-symtom-vuxna",
    eyebrow: "AuDHD i vuxenlivet",
    title: "AuDHD hos vuxna – vanliga drag och mönster | Relationsvarning",
    description: "AuDHD hos vuxna: läs om möjliga mönster kring fokus, rutiner, sensorik, social energi, överstimulering och vardagspåverkan utan att använda listan för diagnos.",
    h1: "AuDHD hos vuxna – vanliga drag och mönster",
    intro: "Vuxenlivet ställer krav på planering, återhämtning, relationer och flexibla byten mellan uppgifter. För personer som funderar på AuDHD kan det vara hjälpsamt att se hur flera områden påverkar varandra, snarare än att leta efter en enda typisk symtombild.",
    parent: { href: "/audhd", label: "Vad är AuDHD?" },
    sections: [
      { heading: "Fokus och igångsättning", paragraphs: ["Att fastna i en uppgift, tappa tråden vid avbrott eller ha svårt att börja kan förekomma i många sammanhang. Det blir mer informativt att beskriva vad som händer i en hel uppgiftskedja: start, prioritering, övergång och avslut.", "Sömn, stress, oro och arbetsmiljö kan påverka samma områden. Enstaka svåra veckor säger därför inte ensamma något säkert om en långvarig neuropsykiatrisk bild."], links: [{ href: "/adhd-vuxna", label: "ADHD hos vuxna" }] },
      { heading: "Rutiner, förändringar och sensorisk belastning", paragraphs: ["Tydliga ramar kan göra en dag lättare, medan plötsliga byten kan ta mycket energi. Ljud, ljus, trängsel eller flera samtal samtidigt kan vara en separat belastning som gör det svårare att använda sådana strategier som annars fungerar.", "Det finns stora individuella skillnader. Sensorisk känslighet eller behov av ordning kan inte på egen hand bekräfta autism eller AuDHD."], links: [{ href: "/autism-vuxna", label: "autism i vuxenlivet" }, { href: "/adhd-eller-autism", label: "skillnader och överlapp" }] },
      { heading: "Social energi och återhämtning", paragraphs: ["En aktivitet kan vara meningsfull och ändå kräva planering eller återhämtning. Vissa blir trötta av många sociala intryck, andra av att hålla reda på praktiska detaljer och avbrott. Att skilja på de delarna kan göra det lättare att formulera behov.", "AuDHD är ett informellt begrepp, inte en separat diagnos. En professionell bedömning behöver titta på utveckling, vardagspåverkan och andra möjliga orsaker."], links: [{ href: "/audhd-masking", label: "masking och kompensation" }, { href: "/audhd-kvinnor", label: "AuDHD hos kvinnor" }] },
    ],
    related: [...common, { href: "/adhd-och-autism-samtidigt", label: "ADHD och autism samtidigt", description: "Om när flera behov behöver förstås sida vid sida." }],
    cta: { title: "Kartlägg områden utan att sätta en etikett", text: "AuDHD-testet tar upp åtta områden i en självskattning för vuxna. Det kan hjälpa dig se ett mönster i svaren, men är inte en diagnos.", href: "/audhd-test", label: "Till AuDHD-testet" },
    faq: [{ question: "Vilka symtom har vuxna med AuDHD?", answer: "Det finns ingen enda symtomprofil. Vuxna kan beskriva olika kombinationer av fokus, struktur, sensorik, social energi, anpassning och vardagspåverkan." }],
  },
} satisfies Record<string, ClusterGuideData>;
