export type Dimension = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H";
export type Question = { id: string; dimension: Dimension; text: string; subpattern: string };

// Fixed mixed order deliberately prevents respondents from being primed by a visible domain.
const source: Record<Dimension, Array<[string, string]>> = {
  A: [["Hur ofta har du svårt att komma igång med något trots att du både vill och behöver göra det?", "aktivering och struktur"], ["Hur ofta tappar du bort dig när en uppgift innehåller flera steg?", "uppmärksamhet och arbetsminne"], ["Hur ofta märker du att tankarna har glidit iväg medan du försöker lyssna eller koncentrera dig?", "uppmärksamhet och arbetsminne"], ["Hur ofta glömmer eller tappar du bort saker du behöver i vardagen?", "vardagsminne"], ["Hur ofta underskattar du hur lång tid något kommer att ta?", "tidshantering"], ["Hur ofta börjar du på något nytt innan du avslutat det du redan höll på med?", "slutförande"], ["Hur ofta glömmer du sådant du faktiskt tycker är viktigt, som tider, ärenden eller saker du lovat att göra?", "vardagsminne"], ["Hur ofta behöver du påminnelser, listor eller andra system för att hålla ihop vardagen?", "aktivering och struktur"]],
  B: [["Hur ofta känner du en inre rastlöshet när du måste vara stilla eller vänta?", "inre rastlöshet"], ["Hur ofta säger eller gör du något innan du hunnit tänka igenom det?", "impulsivitet"], ["Hur ofta söker du extra stimulans när något känns långsamt eller monotont?", "stimulansbehov"], ["Hur ofta fattar du spontana beslut som du senare önskar att du tänkt igenom mer?", "impulsivitet"], ["Hur ofta tappar du intresset för något när nyheten eller spänningen försvinner?", "stimulansbehov"], ["Hur ofta känns det svårt att vänta på din tur när du redan vet vad du vill säga eller göra?", "inre rastlöshet"]],
  C: [["Hur ofta känner du dig osäker på vad som förväntas av dig i en ny social situation?", "sociala förväntningar"], ["Hur ofta behöver du medvetet tolka tonfall, ansiktsuttryck eller kroppsspråk för att förstå vad någon menar?", "tolkning av signaler"], ["Hur ofta upptäcker du i efterhand att någon antydde något som du inte uppfattade då?", "indirekt kommunikation"], ["Hur ofta är det svårt att veta när du ska börja prata, sluta prata eller ta din tur i ett samtal?", "samtalsflyt"], ["Hur ofta blir du trött av socialt umgänge även när du tycker om människorna du är med?", "social energi"], ["Hur ofta är det lättare för dig när människor säger exakt vad de menar istället för att antyda det?", "indirekt kommunikation"], ["Hur ofta analyserar du ett socialt möte efteråt för att förstå hur det gick eller om du gjorde något fel?", "efteranalys"]],
  D: [["Hur ofta påverkar en oväntad ändring av planer dig mer än du tycker att den borde?", "planändringar"], ["Hur ofta vill du veta i förväg hur en situation kommer att gå till?", "förutsägbarhet"], ["Hur ofta blir du så uppslukad av ett intresse att du tappar uppfattningen om tid eller annat omkring dig?", "uppslukande intressen"], ["Hur ofta föredrar du att göra saker på ett välbekant sätt även när andra sätt också skulle fungera?", "välbekanta sätt"], ["Hur ofta är det svårt att växla till något annat när du blivit avbruten mitt i något?", "omställning"], ["Hur ofta återkommer du till samma mat, aktiviteter, innehåll eller rutiner eftersom det känns tryggt eller rätt?", "rutiner"], ["Hur ofta fortsätter ett särskilt intresse eller ämne att ta mycket mental plats även när du gör något annat?", "uppslukande intressen"]],
  E: [["Hur ofta störs du av ljud som andra människor verkar kunna ignorera?", "ljud"], ["Hur ofta blir du påverkad av starkt ljus, mycket rörelse eller visuellt stökiga miljöer?", "visuella intryck"], ["Hur ofta störs du tydligt av hur kläder, material eller beröring känns mot kroppen?", "beröring och material"], ["Hur ofta reagerar du starkt på lukt, smak, temperatur eller andra kroppsliga sinnesintryck?", "övriga sinnesintryck"], ["Hur ofta blir miljöer med många samtidiga intryck så intensiva att du behöver komma därifrån eller återhämta dig efteråt?", "överbelastning"]],
  F: [["Hur ofta förbereder du i huvudet vad du ska säga innan ett socialt möte?", "förberedelse"], ["Hur ofta studerar eller härmar du andra för att veta hur du själv ska bete dig socialt?", "inlärda strategier"], ["Hur ofta håller du tillbaka naturliga rörelser, reaktioner eller intressen för att inte sticka ut?", "att hålla tillbaka"], ["Hur ofta verkar du socialt avslappnad utåt samtidigt som du aktivt tänker på hur du beter dig?", "aktiv anpassning"], ["Hur ofta behöver du återhämtning efter att länge ha försökt fungera på ett sätt som andra förväntar sig?", "kostnaden för anpassning"]],
  G: [["Hur ofta längtar du efter fasta rutiner men samtidigt blir uttråkad av dem eller får svårt att följa dem?", "struktur kontra svårt att följa struktur"], ["Hur ofta söker du nya intryck eller upplevelser men blir överbelastad när det blir för mycket?", "stimulans kontra överstimulering"], ["Hur ofta uppskattar du spontanitet när den kommer från dig själv men blir stressad när någon annan plötsligt ändrar planen?", "självvald spontanitet kontra externa planändringar"], ["Hur ofta vill du ha ordning och tydliga system men har svårt att själv hålla systemen igång?", "behov av system kontra svårt att upprätthålla system"], ["Hur ofta vill en del av dig ha variation samtidigt som en annan del av dig vill att saker ska vara förutsägbara?", "variation kontra förutsägbarhet"]],
  H: [["Hur ofta gör de här typerna av svårigheter vanliga vardagsuppgifter betydligt mer ansträngande?", "vardagsuppgifter"], ["Hur ofta påverkar de din förmåga att fungera i arbete, studier eller andra kravfyllda uppgifter?", "arbete eller studier"], ["Hur ofta skapar de problem eller missförstånd i relationer med andra människor?", "relationer"], ["Hur ofta blir dina känslor svåra att reglera när du är överstimulerad, frustrerad eller överbelastad?", "reglering vid belastning"], ["Hur ofta känner du dig ovanligt utmattad av att få vardagen att fungera?", "energi och återhämtning"]],
};

const mixed: Array<[Dimension, number]> = [["A",0],["C",0],["G",0],["E",0],["B",0],["D",0],["F",0],["H",0],["A",1],["C",1],["E",1],["B",1],["D",1],["G",1],["F",1],["H",1],["A",2],["C",2],["D",2],["E",2],["B",2],["G",2],["F",2],["H",2],["A",3],["C",3],["D",3],["B",3],["E",3],["G",3],["F",3],["H",3],["A",4],["C",4],["D",4],["E",4],["B",4],["G",4],["F",4],["H",4],["A",5],["C",5],["D",5],["B",5],["A",6],["C",6],["D",6],["A",7]];
export const questions: Question[] = mixed.map(([dimension, index]) => ({ id: `${dimension}${index + 1}`, dimension, text: source[dimension][index][0], subpattern: source[dimension][index][1] }));
export const contextQuestions = [
  { id: "K1", text: "När du tänker tillbaka på barndomen, fanns många av de här dragen eller svårigheterna redan då?", options: ["Nej, inte vad jag känner igen", "I liten utsträckning", "Delvis", "Ja, tydligt", "Jag är osäker"] },
  { id: "K2", text: "Märker du liknande mönster inom flera delar av livet, exempelvis hemma, socialt och i arbete eller studier?", options: ["Nej, främst i en situation", "I några situationer", "I flera delar av livet", "I nästan alla viktiga delar av livet", "Jag är osäker"] },
  { id: "K3", text: "Hur mycket påverkar svårigheterna arbete, studier eller andra krav?", options: ["Inte alls", "Lite", "Måttligt", "Mycket", "Extremt mycket"] },
  { id: "K4", text: "Hur mycket påverkar de relationer eller socialt liv?", options: ["Inte alls", "Lite", "Måttligt", "Mycket", "Extremt mycket"] },
  { id: "K5", text: "Hur mycket energi går åt till strategier för att dölja, kompensera för eller hantera svårigheterna?", options: ["Ingen eller nästan ingen", "Lite", "En del", "Mycket", "Väldigt mycket"] },
  { id: "K6", text: "Har merparten av svårigheterna blivit tydliga först under de senaste åren?", options: ["Nej", "Delvis, men mönstret är äldre", "Ja, till stor del", "Jag är osäker"] },
] as const;
