import Link from "next/link";
import EditorialSurface from "./EditorialSurface";
import { GuideSection, textLink } from "./ContentGuide";
import { EditorialArticleJsonLd, getEditorialArticleSchema } from "../_seo/editorialSeo";

type Props = { route: `/${string}`; title: string; description: string; intro: string; sections: Array<{ title: string; paragraphs: string[] }>; links: Array<{ href: string; label: string }> };
export default function AngestGuide({ route, title, description, intro, sections, links }: Props) {
  const articleJsonLd = getEditorialArticleSchema({ route, title, description, datePublished: "2026-09-24T12:00:00+02:00", dateModified: "2026-09-24T12:00:00+02:00" });
  return <EditorialSurface><main data-rv="container" className="mx-auto max-w-3xl px-4 py-10 text-neutral-900 sm:px-6 sm:py-14"><EditorialArticleJsonLd data={articleJsonLd} /><nav aria-label="Brödsmulor" className="text-sm text-neutral-600"><Link href="/" className={textLink}>Relationsvarning</Link><span aria-hidden="true"> / </span><Link href="/angest-test" className={textLink}>Ångesttest</Link><span aria-hidden="true"> / </span><span aria-current="page">{title}</span></nav><article><header className="mt-5"><h1 className="text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">{title}</h1><p className="mt-5 text-lg leading-8 text-neutral-700">{intro}</p></header>{sections.map(section => <GuideSection key={section.title} title={section.title}>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</GuideSection>)}<GuideSection title="Utforska ditt eget mönster"><p>Relationsvarnings ångesttest är en icke-diagnostisk självskattning med 30 frågor om oro, kroppslig anspänning, sömn och vardagspåverkan.</p><Link data-rv="button" href="/angest-test/test" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-neutral-900 px-5 py-3 font-semibold text-white hover:bg-neutral-800">Starta ångesttestet</Link></GuideSection><GuideSection title="Läs vidare"><ul className="space-y-3">{links.map(link => <li key={link.href}><Link href={link.href} className={textLink}>{link.label}</Link></li>)}</ul></GuideSection><p className="mt-8 text-sm leading-6 text-neutral-600">Texten är allmän information och ersätter inte vårdens bedömning. Vid akut fara eller självmordstankar: ring 112. För sjukvårdsråd: ring 1177.</p></article></main></EditorialSurface>;
}
