import type { TestId } from "../_analytics/config";

export type GuideLink = { title: string; description: string; href: string };
export type GuideRecommendation = {
  related: GuideLink[];
  test?: { title: string; description: string; label: string; testId: TestId };
};

const guide = (title: string, href: string, description: string): GuideLink => ({ title, href, description });
const test = (testId: TestId, title: string, description: string, label: string) => ({ testId, title, description, label });

// Editorially selected destinations. Safety and support pages intentionally have no commercial test card.
export const guideRecommendations: Record<string, GuideRecommendation> = {
  "/svartsjuk-partner": { related: [guide("Kontrollerande relation", "/kontrollerande-relation", "När svartsjuka blir regler och begränsningar."), guide("Gränser i relation", "/granser-i-relation", "Om rätten till eget utrymme och ett nej.")], test: test("screening_test", "Vill du se mönstret i ett större sammanhang?", "Relationstestet hjälper dig att strukturera återkommande beteenden i relationen.", "Gör relationstestet") },
  "/stanna-eller-ga": { related: [guide("Destruktivt förhållande", "/destruktivt-forhallande", "Tecken på mönster som påverkar trygghet och frihet."), guide("Traumabindning i relation", "/traumabindning-i-relation", "Om varför det kan vara svårt att lämna trots att du mår dåligt.")], test: test("screening_test", "Vill du få syn på återkommande mönster?", "Relationstestet kan ge en struktur för dina egna iakttagelser utan att fatta beslut åt dig.", "Gör relationstestet") },
  "/stanna-eller-ga/gar-relationen-att-radda": { related: [guide("Stanna eller gå", "/stanna-eller-ga", "Fler frågor om trygghet, ansvar och beslut."), guide("Gränser i relation", "/granser-i-relation", "Hur respekt för gränser märks i vardagen.")], test: test("screening_test", "Vill du undersöka relationens mönster?", "Ett strukturerat sätt att reflektera över dina egna upplevelser.", "Gör relationstestet") },
  "/granser-i-relation": { related: [guide("Medberoende", "/medberoende", "När omsorg om andra tränger undan egna behov."), guide("Kontrollerande relation", "/kontrollerande-relation", "När önskemål övergår i regler och press.")], test: test("screening_test", "Hur fungerar gränserna i din relation?", "Undersök flera återkommande relationsmönster utifrån din situation.", "Gör relationstestet") },
  "/granser-i-relation/partner-blir-arg-nar-jag-sager-nej": { related: [guide("Gränser i relation", "/granser-i-relation", "Om ett nej och rätten till eget utrymme."), guide("Kontrollerande relation", "/kontrollerande-relation", "När ilska och press blir ett sätt att styra.")], test: test("screening_test", "Vill du se om fler mönster återkommer?", "Relationstestet ger en struktur för att reflektera över beteenden och trygghet.", "Gör relationstestet") },
  "/stonewalling-relation": { related: [guide("Silent treatment", "/silent-treatment-relation", "När tystnad används som straff eller maktmedel."), guide("Undvikande anknytning", "/anknytning/undvikande-anknytning", "Om avstånd, sårbarhet och behovet av återhämtning.")], test: test("screening_test", "Vill du se hur fler mönster samspelar?", "Relationstestet hjälper dig att strukturera det du upplever i relationen.", "Gör relationstestet") },
  "/adhd-och-relationer": { related: [guide("ADHD i vardagen", "/adhd-i-vardagen", "Rutiner, tid och återhämtning i vardagslivet."), guide("ADHD hos vuxna", "/adhd-vuxna", "Ett bredare perspektiv på ADHD-relaterade svårigheter.")], test: test("adhd_test", "Vill du kartlägga din egen vardag?", "ADHD-testet är en självskattning av olika mönster och kan inte ställa diagnos.", "Gör ADHD-testet") },
  "/adhd-och-relationer/partner-med-adhd": { related: [guide("ADHD och relationer", "/adhd-och-relationer", "Om närhet, konflikt och ansvar ur bådas perspektiv."), guide("ADHD i vardagen", "/adhd-i-vardagen", "Hur vardagens strukturer kan påverkas.")] },
  "/destruktivt-forhallande": { related: [guide("Stanna eller gå", "/stanna-eller-ga", "Frågor om trygghet, ansvar och förändring."), guide("Traumabindning i relation", "/traumabindning-i-relation", "När närhet och smärta gör relationen svår att lämna.")], test: test("screening_test", "Vill du strukturera det du upplever?", "Undersök flera relationsmönster utan att testet bestämmer vad du ska göra.", "Gör relationstestet") },
  "/silent-treatment-relation": { related: [guide("Stonewalling", "/stonewalling-relation", "Skillnaden mellan en paus och bestraffande tystnad."), guide("Undvikande anknytning", "/anknytning/undvikande-anknytning", "Om närhet och avstånd i relationer.")], test: test("screening_test", "Vill du undersöka relationen bredare?", "Relationstestet hjälper dig att sätta återkommande tystnad i ett större sammanhang.", "Gör relationstestet") },
  "/love-bombing-relation": { related: [guide("Kontrollerande relation", "/kontrollerande-relation", "När stark intensitet följs av begränsningar."), guide("Destruktivt förhållande", "/destruktivt-forhallande", "Hur mönster utvecklas över tid.")], test: test("screening_test", "Vill du se relationens mönster över tid?", "Undersök flera beteenden utifrån dina egna erfarenheter.", "Gör relationstestet") },
  "/medberoende-i-relation": { related: [guide("Medberoende", "/medberoende", "Ett bredare perspektiv på överansvar och egna behov."), guide("Gränser i relation", "/granser-i-relation", "När ett nej behöver få finnas kvar.")], test: test("codependency_test", "Vill du undersöka ditt eget ansvarsmönster?", "Medberoendetestet fokuserar på gränser, omsorg och egna behov.", "Gör medberoendetestet") },
  "/anknytning": { related: [guide("Ängslig anknytning", "/anknytning/angslig-anknytning", "Om oro och behov av bekräftelse."), guide("Undvikande anknytning", "/anknytning/undvikande-anknytning", "Om avstånd och självständighet.")], test: test("attachment_test", "Vill du utforska dina anknytningsmönster?", "Anknytningstestet ger en struktur för att reflektera över närhet, avstånd och trygghet.", "Gör anknytningstestet") },
  "/medberoende": { related: [guide("Tecken på medberoende", "/medberoende/tecken", "Vanliga uttryck för överansvar."), guide("Bryta medberoende", "/medberoende/bryta-medberoende", "Om gränser och förändring i vardagen.")], test: test("codependency_test", "Vill du undersöka dina egna mönster?", "Medberoendetestet hjälper dig att reflektera över ansvar, gränser och behov.", "Gör medberoendetestet") },
  "/adhd-vuxna": { related: [guide("ADHD-symtom hos vuxna", "/adhd-symtom-vuxna", "Hur mönster kan märkas i vardagen."), guide("ADHD i vardagen", "/adhd-i-vardagen", "Exempel från arbete, hem och återhämtning.")], test: test("adhd_test", "Vill du kartlägga din egen vardag?", "Självtestet hjälper dig att strukturera ADHD-relaterade upplevelser utan att ställa diagnos.", "Gör ADHD-testet") },
  "/har-jag-adhd": { related: [guide("ADHD hos vuxna", "/adhd-vuxna", "Se flera mönster och möjliga förklaringar."), guide("ADHD-symtom hos vuxna", "/adhd-symtom-vuxna", "Konkreta uttryck i vardagen.")], test: test("adhd_test", "Vill du strukturera dina egna svar?", "ADHD-testet är ett reflektionsstöd och kan inte ställa diagnos.", "Gör ADHD-testet") },
  "/add-test": { related: [guide("ADHD utan hyperaktivitet", "/adhd-utan-hyperaktivitet", "När svårigheterna främst märks som ouppmärksamhet."), guide("ADHD hos vuxna", "/adhd-vuxna", "Ett bredare perspektiv på ADHD i vuxenlivet.")], test: test("adhd_test", "Vill du kartlägga fler områden?", "Självtestet tar upp olika ADHD-relaterade mönster utan att ge en diagnos.", "Gör ADHD-testet") },
  "/adhd-kvinnor": { related: [guide("ADHD-symtom hos kvinnor", "/adhd-kvinnor-symtom", "Hur mönster kan visa sig och döljas."), guide("ADHD i vardagen", "/adhd-i-vardagen", "Om rutiner, energi och återhämtning.")], test: test("adhd_test", "Vill du undersöka dina egna vardagsmönster?", "ADHD-testet ger en strukturerad självskattning, inte en diagnos.", "Gör ADHD-testet") },
  "/adhd-kvinnor-symtom": { related: [guide("ADHD hos kvinnor", "/adhd-kvinnor", "Fördjupning om sammanhang och variation."), guide("ADHD-symtom hos vuxna", "/adhd-symtom-vuxna", "Jämför med ett bredare vuxenperspektiv.")], test: test("adhd_test", "Vill du se helheten i dina svar?", "Självtestet hjälper dig att strukturera flera ADHD-relaterade områden.", "Gör ADHD-testet") },
  "/adhd-symtom-vuxna": { related: [guide("ADHD hos vuxna", "/adhd-vuxna", "Hur symtom och vardagspåverkan hänger ihop."), guide("ADHD i vardagen", "/adhd-i-vardagen", "Konkreta situationer i arbete och hemma.")], test: test("adhd_test", "Vill du kartlägga mönstren hos dig själv?", "Självtestet hjälper dig att reflektera över flera områden utan att ställa diagnos.", "Gör ADHD-testet") },
  "/adhd-utan-hyperaktivitet": { related: [guide("ADD-test", "/add-test", "Vad begreppet kan och inte kan säga."), guide("ADHD-symtom hos vuxna", "/adhd-symtom-vuxna", "Fler uttryck än synlig rastlöshet.")], test: test("adhd_test", "Vill du undersöka fler vardagsmönster?", "ADHD-testet omfattar både uppmärksamhet och andra områden.", "Gör ADHD-testet") },
  "/adhd-i-vardagen": { related: [guide("ADHD hos vuxna", "/adhd-vuxna", "Den bredare bilden av ADHD i vuxenlivet."), guide("ADHD och relationer", "/adhd-och-relationer", "När vardagsmönster påverkar samspelet.")], test: test("adhd_test", "Hur stämmer mönstren med din vardag?", "Självtestet ger en struktur för dina egna iakttagelser.", "Gör ADHD-testet") },
  "/autism-vuxna": { related: [guide("Autismsymtom hos vuxna", "/autism-symtom-vuxna", "Vanliga uttryck och variationer."), guide("Maskering vid autism", "/maskering-autism", "När anpassning döljer ansträngning.")], test: test("autism_test", "Vill du strukturera dina egna erfarenheter?", "Autismtestet är en självskattning och kan inte ställa diagnos.", "Gör autismtestet") },
  "/har-jag-autism": { related: [guide("Autism hos vuxna", "/autism-vuxna", "Se helheten bortom enskilda igenkänningstecken."), guide("Autismsymtom hos vuxna", "/autism-symtom-vuxna", "Hur olika mönster kan märkas.")], test: test("autism_test", "Vill du strukturera det du känner igen?", "Autismtestet är ett reflektionsstöd och kan inte ställa diagnos.", "Gör autismtestet") },
  "/autism-symtom-vuxna": { related: [guide("Autism hos vuxna", "/autism-vuxna", "Mönster över tid och i olika miljöer."), guide("Maskering vid autism", "/maskering-autism", "När anpassning påverkar vad andra ser.")], test: test("autism_test", "Vill du undersöka dina egna erfarenheter?", "Självtestet samlar flera områden i en struktur utan att ställa diagnos.", "Gör autismtestet") },
  "/autism-kvinnor": { related: [guide("Autismsymtom hos kvinnor", "/autism-kvinnor-symtom", "Konkreta uttryck och variationer."), guide("Maskering vid autism", "/maskering-autism", "Om anpassning och återhämtning.")], test: test("autism_test", "Vill du se flera områden tillsammans?", "Självtestet ger en strukturerad bild av dina svar, inte en diagnos.", "Gör autismtestet") },
  "/autism-kvinnor-symtom": { related: [guide("Autism hos kvinnor", "/autism-kvinnor", "En bredare genomgång av sammanhanget."), guide("Maskering vid autism", "/maskering-autism", "När yttre anpassning döljer ansträngning.")], test: test("autism_test", "Vill du strukturera dina egna svar?", "Självtestet hjälper dig att reflektera över flera autismrelaterade områden.", "Gör autismtestet") },
  "/maskering-autism": { related: [guide("Autism hos vuxna", "/autism-vuxna", "Se fler mönster än det som syns utåt."), guide("Autism hos kvinnor", "/autism-kvinnor", "Om variation och anpassning i vardagen.")], test: test("autism_test", "Vill du se fler delar av din vardag?", "Självtestet ger en struktur för reflektion men kan inte ställa diagnos.", "Gör autismtestet") },
  "/asperger-test": { related: [guide("Autism hos vuxna", "/autism-vuxna", "Nutida begrepp och hur autism kan märkas."), guide("Autismsymtom hos vuxna", "/autism-symtom-vuxna", "Fler exempel från vuxenlivet.")], test: test("autism_test", "Vill du utforska dina egna mönster?", "Autismtestet är en självskattning och kan inte bekräfta eller utesluta autism.", "Gör autismtestet") },
  "/adhd-autism": { related: [guide("ADHD hos vuxna", "/adhd-vuxna", "Hur ADHD-relaterade mönster kan märkas."), guide("Autism hos vuxna", "/autism-vuxna", "Ett separat perspektiv på autismrelaterade mönster.")] },
};
