import type { Metadata } from "next";
import Link from "next/link";
import EditorialSurface from "../_components/EditorialSurface";
import { GuideSection, textLink } from "../_components/ContentGuide";
import { EditorialArticleJsonLd, getEditorialArticleSchema, getEditorialMetadata } from "../_seo/editorialSeo";

const title = "Högkänslig eller ADHD? Skillnader och likheter | Relationsvarning";
const description = "Högkänslighet och ADHD kan båda innebära överstimulering och starka reaktioner på intryck. Se viktiga likheter och skillnader och när det kan vara värt att söka vård.";
export const metadata: Metadata = { title, description, robots: { index: true, follow: true }, ...getEditorialMetadata({ route: "/hogkanslig-eller-adhd", title, description, datePublished: "2026-09-28T14:00:00+02:00", dateModified: "2026-09-28T14:00:00+02:00" }) };
const article = getEditorialArticleSchema({ route: "/hogkanslig-eller-adhd", title, description, datePublished: "2026-09-28T14:00:00+02:00", dateModified: "2026-09-28T14:00:00+02:00" });
const cta = "inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-[#27666A] px-5 py-3 text-center font-semibold text-white transition hover:bg-[#1F5357] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#27666A] sm:w-auto";
const comparison = [["Överstimulering", "Kan förekomma vid hög känslighet för stimuli.", "Kan förekomma vid svårigheter att filtrera, reglera och hantera många samtidiga stimuli."], ["Sensorisk känslighet", "Kan vara en central del av personens känslighetsprofil.", "Kan förekomma, men är inte ett krav för diagnos."], ["Koncentration", "Kan störas i överstimulerande miljöer.", "Varaktiga svårigheter med uppmärksamhet och reglering är centrala delar av tillståndet."], ["Impulsivitet", "Är inte ett definierande drag.", "Kan vara ett centralt symtom."], ["Barndom", "Beskrivs som ett personlighets- eller temperamentsdrag.", "Diagnostiska symtom ska ha funnits sedan barndomen."], ["Diagnos", "Nej.", "Ja, neuropsykiatrisk diagnos."]] as const;
const faqs = [["Är HSP samma sak som ADHD?", "Nej. ADHD är en neuropsykiatrisk diagnos. HSP eller högkänslighet är inte en diagnos."], ["Kan ADHD göra en känslig för ljud och intryck?", "Ja, personer med ADHD kan uppleva överstimulering eller känslighet för vissa typer av stimuli. Det är dock inte tillräckligt för att avgöra om någon har ADHD."], ["Kan man vara både högkänslig och ha ADHD?", "Ja. Hög känslighet och ADHD utesluter inte varandra."], ["Hur vet jag om jag har ADHD?", "ADHD diagnostiseras genom en professionell bedömning där man bland annat tittar på långvariga symtom, funktionspåverkan och hur personen fungerat sedan barndomen."], ["Kan ett HSP-test visa om jag har ADHD?", "Nej. Ett HSP-test kan beskriva din känslighetsprofil men kan inte diagnostisera ADHD."]] as const;
const schema = [{ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Startsida", item: "https://www.relationsvarning.se/" }, { "@type": "ListItem", position: 2, name: "Artiklar", item: "https://www.relationsvarning.se/" }, { "@type": "ListItem", position: 3, name: "Högkänslig eller ADHD", item: "https://www.relationsvarning.se/hogkanslig-eller-adhd" }] }];

export default function SensitiveOrAdhdPage() {
  return <EditorialSurface><main data-rv="container" className="mx-auto max-w-4xl px-4 py-8 text-neutral-900 sm:px-6 sm:py-14"><EditorialArticleJsonLd data={article} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
    <nav aria-label="Brödsmulor" className="text-sm text-neutral-600"><Link href="/" className={textLink}>Relationsvarning</Link> / <span>Artiklar</span> / <span aria-current="page">Högkänslig eller ADHD</span></nav>
    <article><header className="mt-6 rounded-[28px] border border-[#D6E1DD] bg-[#FFFEFC] px-5 py-8 shadow-sm sm:px-9 sm:py-12"><p className="text-sm font-semibold uppercase tracking-[.16em] text-[#27666A]">HSP och ADHD</p><h1 className="mt-3">Högkänslig eller ADHD – vad är skillnaden?</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-neutral-700">Högkänslighet och ADHD kan ibland kännas lika i vardagen. Båda kan innebära överstimulering, känslighet för sinnesintryck och behov av återhämtning. Men de beskriver inte samma sak.</p><p className="mt-4 font-semibold text-[#364A4B]">ADHD är en neuropsykiatrisk diagnos. HSP/högkänslighet är inte en diagnos.</p></header>
      <GuideSection title="Likheter och skillnader mellan HSP och ADHD"><p className="max-w-3xl">Jämförelsen kan hjälpa dig att sätta ord på upplevelser, men den är inte ett diagnostiskt verktyg.</p><div className="overflow-hidden rounded-2xl border border-neutral-200"><div className="hidden grid-cols-[minmax(9rem,1fr)_minmax(0,1fr)_minmax(0,1fr)] bg-[#f3f4ef] p-4 text-sm font-semibold sm:grid"><span>Område</span><span>HSP/högkänslighet</span><span>ADHD</span></div>{comparison.map(([area, hsp, adhd]) => <div key={area} className="grid gap-2 border-t border-neutral-200 p-4 text-sm leading-6 sm:grid-cols-[minmax(9rem,1fr)_minmax(0,1fr)_minmax(0,1fr)]"><h3 className="font-semibold text-neutral-950">{area}</h3><p><span className="font-semibold sm:hidden">HSP: </span>{hsp}</p><p><span className="font-semibold sm:hidden">ADHD: </span>{adhd}</p></div>)}</div></GuideSection>
      <GuideSection title="Varför kan HSP och ADHD kännas lika?"><p>Överstimulering, sensorisk känslighet, stresskänslighet, social utmattning och starka känslomässiga reaktioner kan vara igenkännbara oavsett förklaring. Liknande upplevelser kan ha olika orsaker. Därför går det inte att avgöra ADHD genom att enbart titta på känslighet för stimuli.</p></GuideSection>
      <GuideSection title="Vad talar mer för ADHD än enbart högkänslighet?"><div className="max-w-3xl space-y-4"><p>Långvariga svårigheter att styra uppmärksamheten, komma igång eller avsluta uppgifter, planera, organisera och hantera tid kan tala för att ADHD behöver undersökas närmare. Impulsivitet eller rastlöshet kan också vara relevanta delar för vissa.</p><p>Vid ADHD väger en bedömning även in om svårigheterna har funnits sedan barndomen, märks i flera delar av livet och påverkar vardagsfungerandet. Inget enskilt drag avgör saken.</p><Link data-rv="button" href="/adhd-test" className={cta}>Gör vårt ADHD-test för vuxna</Link></div></GuideSection>
      <GuideSection title="Vad kan passa bättre med hög känslighet?"><div className="max-w-3xl space-y-4"><p>Stark mottaglighet för subtila detaljer, djup bearbetning, sensorisk känslighet och respons på positiva upplevelser kan vara centrala delar av en känslighetsprofil. Överstimulering utan typiska långvariga svårigheter med uppmärksamhetsreglering och impulsivitet kan också vara en viktig skillnad att reflektera över.</p><p>Detta utesluter inte samtidig ADHD. <Link href="/hsp-test" className={textLink}>Utforska din känslighetsprofil med HSP-testet</Link>.</p></div></GuideSection>
      <GuideSection title="Kan man vara högkänslig och ha ADHD?"><p>Ja, egenskaper som beskrivs som hög känslighet kan förekomma hos personer med ADHD också. HSP och ADHD är inte ömsesidigt uteslutande begrepp.</p><p>Ett självtest kan hjälpa dig att reflektera över dina mönster, men om du har långvariga ADHD-liknande svårigheter som påverkar vardagen är en vårdbedömning mer relevant än ett HSP-test.</p></GuideSection>
      <GuideSection title="När kan det vara värt att söka vård?"><p>Om problem med koncentration, impulsivitet, planering, rastlöshet eller vardagsfunktion är långvariga och påverkar arbete, studier, relationer eller andra delar av livet kan det vara rimligt att kontakta vården för bedömning.</p></GuideSection>
      <section className="mt-10 grid gap-4 sm:grid-cols-2"><div data-rv="card" className="rounded-2xl border border-[#d8d5c8] bg-[#faf8f0] p-5"><h2 className="text-xl font-semibold text-neutral-950">Utforska högkänslighet</h2><p className="mt-2 text-sm leading-6">Se hur sex områden av känslighet förhåller sig till varandra i dina svar.</p><Link data-rv="button" href="/hsp-test" className={`${cta} mt-5`}>Gör HSP-testet</Link></div><div data-rv="card" className="rounded-2xl border border-[#DDE8E3] bg-[#EFF5F2] p-5"><h2 className="text-xl font-semibold text-neutral-950">Utforska ADHD</h2><p className="mt-2 text-sm leading-6">Reflektera över fokus, organisation, tid, impulsivitet och vardagspåverkan.</p><Link data-rv="button" href="/adhd-test" className={`${cta} mt-5`}>Gör ADHD-testet</Link></div></section>
      <GuideSection title="Vanliga frågor om HSP eller ADHD"><div className="divide-y divide-neutral-200 border-y border-neutral-200">{faqs.map(([question, answer]) => <div key={question} className="py-5"><h3 className="font-semibold text-neutral-950">{question}</h3><p className="mt-2 text-sm leading-6">{answer}</p></div>)}</div></GuideSection>
    </article>
  </main></EditorialSurface>;
}
