import type { Metadata } from "next";
import Link from "next/link";
import EditorialSurface from "../_components/EditorialSurface";
import { EditorialArticleJsonLd, getEditorialArticleSchema, getEditorialMetadata } from "../_seo/editorialSeo";
import { GuideSection, textLink } from "../_components/ContentGuide";

const title = "HSP-test – är du högkänslig? Test för vuxna | Relationsvarning";
const description = "Gör ett HSP-test för vuxna med 30 frågor om högkänslighet, överstimulering, känslor och sinnesintryck. Få en personlig profil direkt.";
export const metadata: Metadata = { title, description, ...getEditorialMetadata({ route: "/hsp-test", title, description, datePublished: "2026-09-28T12:00:00+02:00", dateModified: "2026-09-28T12:00:00+02:00" }) };
const article = getEditorialArticleSchema({ route: "/hsp-test", title, description, datePublished: "2026-09-28T12:00:00+02:00", dateModified: "2026-09-28T12:00:00+02:00" });
const cta = "inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-[#9d5663] px-5 py-3 text-center font-semibold text-white transition hover:bg-[#844451] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#576f60] sm:w-auto";

const areas = [
  ["Överstimulering", "Hur lätt många samtidiga intryck och krav blir överväldigande."],
  ["Sensorisk känslighet", "Hur starkt du reagerar på exempelvis ljud, ljus, dofter och beröring."],
  ["Emotionell reaktivitet", "Hur starkt och länge känslomässiga upplevelser påverkar dig."],
  ["Djup bearbetning", "Hur mycket du analyserar, reflekterar och bearbetar upplevelser."],
  ["Social känslighet", "Hur lätt du registrerar stämningar, tonfall och andra människors känslor."],
  ["Positiv känslighet & detaljer", "Hur starkt du påverkas av subtila detaljer, musik, natur och positiva upplevelser."],
] as const;
const benefits = [["Din känslighetsprofil", "Se hur dina olika typer av känslighet förhåller sig till varandra."], ["Ditt tydligaste mönster", "Vi identifierar den del eller kombination som är mest intressant i dina svar."], ["Personlig tolkning", "Resultatet anpassas efter hur du faktiskt har svarat."]] as const;
const recognition = ["Du blir snabbt trött av mycket ljud, människor eller aktivitet.", "Du märker små förändringar i tonfall eller stämningar.", "Kritik eller starka upplevelser kan stanna kvar länge.", "Du behöver återhämtning efter intensiva dagar.", "Musik, natur eller andra positiva upplevelser kan påverka dig starkt.", "Du tenderar att tänka igenom saker grundligt."] as const;
const faqs = [["Är HSP en diagnos?", "Nej. HSP/högkänslighet används för att beskriva ett personlighets- eller temperamentsdrag, inte en medicinsk eller psykiatrisk diagnos."], ["Hur fungerar HSP-testet?", "Du svarar på 30 frågor och får en profil över sex områden relaterade till hur du bearbetar och reagerar på olika typer av intryck."], ["Hur lång tid tar testet?", "Cirka fem minuter för de flesta."], ["Kan HSP likna ADHD eller autism?", "Det kan finnas överlappande upplevelser, till exempel sensorisk känslighet och överstimulering. Testet kan däremot inte diagnostisera eller avgöra orsaken till sådana besvär."], ["Kan testet säga säkert om jag är högkänslig?", "Nej. Resultatet ska ses som ett självskattningsresultat och en beskrivning av dina svar, inte som en medicinsk bedömning."]] as const;
const supplementalSchema = [{ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Startsida", item: "https://www.relationsvarning.se/" }, { "@type": "ListItem", position: 2, name: "Självtester", item: "https://www.relationsvarning.se/" }, { "@type": "ListItem", position: 3, name: "HSP-test", item: "https://www.relationsvarning.se/hsp-test" }] }];

export default function HspLanding() {
  return <EditorialSurface><main data-rv="container" className="mx-auto max-w-4xl px-4 py-8 text-neutral-900 sm:px-6 sm:py-14"><EditorialArticleJsonLd data={article} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(supplementalSchema).replace(/</g, "\\u003c") }} />
    <nav aria-label="Brödsmulor" className="text-sm text-neutral-600"><Link href="/" className={textLink}>Relationsvarning</Link> / <span>Självtester</span> / <span aria-current="page">HSP-test</span></nav>
    <article><header className="mt-6 rounded-[28px] border border-[#e6d9d7] bg-[#fffaf8] px-5 py-8 shadow-sm sm:px-9 sm:py-12"><p className="text-sm font-semibold uppercase tracking-[.16em] text-[#9d5663]">HSP-test för vuxna</p><h1 className="mt-3 max-w-3xl">HSP-test: Är du högkänslig?</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-neutral-700">Gör ett HSP-test med 30 frågor om hur du reagerar på intryck, känslor, sociala signaler och överstimulering. Du får en personlig profil över sex områden.</p><div className="mt-7"><Link data-rv="button" href="/hsp-test/test" className={cta}>Starta HSP-testet</Link></div><p className="mt-3 text-sm font-semibold text-neutral-700">30 frågor · cirka 5 minuter · resultat direkt</p><p className="mt-4 text-sm text-neutral-600">Ingen registrering krävs</p></header>

      <GuideSection title="Högkänslighet ser inte likadan ut hos alla"><p className="max-w-3xl">Två personer kan båda känna igen sig i högkänslighet men reagera väldigt olika. Därför tittar testet inte bara på ett totalresultat utan på sex olika delar av din känslighetsprofil.</p><div className="grid gap-3 sm:grid-cols-2">{areas.map(([heading, copy]) => <div data-rv="card" key={heading} className="min-w-0 rounded-2xl border border-neutral-200 bg-neutral-50 p-5"><h3 className="font-semibold text-neutral-950">{heading}</h3><p className="mt-2 text-sm leading-6">{copy}</p></div>)}</div><Link data-rv="button" href="/hsp-test/test" className={cta}>Gör testet</Link></GuideSection>

      <GuideSection title="Du får mer än bara en totalsiffra"><p>Dina svar jämförs mellan de sex områdena för att hitta mönster, kontraster och kombinationer i just din profil.</p><div className="grid gap-3 sm:grid-cols-3">{benefits.map(([heading, copy]) => <div data-rv="card" key={heading} className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5"><h3 className="font-semibold text-neutral-950">{heading}</h3><p className="mt-2 text-sm leading-6">{copy}</p></div>)}</div></GuideSection>

      <GuideSection title="Vad är HSP och högkänslighet?"><div className="max-w-3xl space-y-4"><p>HSP står för <em>Highly Sensitive Person</em>. Inom forskning används ofta begreppet <em>Sensory Processing Sensitivity</em> (SPS) för att beskriva individuella skillnader i hur människor tar in, bearbetar och reagerar på stimuli och erfarenheter.</p><p>Högkänslighet är inte en psykiatrisk diagnos. Att vara känslig för ljud, sociala signaler eller starka upplevelser räcker inte i sig för att förklara varför en person mår eller fungerar på ett visst sätt. Liknande upplevelser kan också förekomma vid till exempel stress, ångest, ADHD eller autism.</p><p>Känslighet kan innebära belastning när många intryck eller krav samlas samtidigt. Den kan också rymma positiva sidor, som detaljuppmärksamhet, djup reflektion eller mottaglighet för musik, natur och sociala nyanser. Självtestet hjälper dig att strukturera dina egna svar, inte att sätta en etikett på dig.</p><p><Link href="/hogkanslig-personlighet" className={textLink}>Läs mer om högkänslig personlighet</Link> eller <Link href="/hogkanslig-eller-adhd" className={textLink}>läs om högkänslig eller ADHD</Link>.</p></div></GuideSection>

      <GuideSection title="Känner du igen något av det här?"><ul className="grid gap-3 sm:grid-cols-2">{recognition.map((item) => <li data-rv="card" key={item} className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4 text-sm leading-6">{item}</li>)}</ul><p>Du behöver inte känna igen dig i allt. Testet tittar på hur just dina olika områden förhåller sig till varandra.</p><Link data-rv="button" href="/hsp-test/test" className={cta}>Starta HSP-testet</Link></GuideSection>

      <GuideSection title="HSP är inte samma sak som ADHD eller autism"><div className="max-w-3xl space-y-4"><p>Överstimulering, starka reaktioner på sinnesintryck och behov av återhämtning kan förekomma av flera olika anledningar. HSP är inte en diagnos och testet kan inte avgöra om dina upplevelser exempelvis beror på ADHD, autism, ångest eller något annat.</p><p><Link href="/adhd-test" className={textLink}>Gör ADHD-testet</Link> eller <Link href="/autism-test" className={textLink}>gör autismtestet</Link> om du vill undersöka de områdena separat.</p></div></GuideSection>

      <GuideSection title="Vanliga frågor om HSP-testet"><div className="divide-y divide-neutral-200 border-y border-neutral-200">{faqs.map(([question, answer]) => <div key={question} className="py-5"><h3 className="font-semibold text-neutral-950">{question}</h3><p className="mt-2 max-w-3xl text-sm leading-6">{answer}</p></div>)}</div></GuideSection>
      <section data-rv="panel" className="mt-12 rounded-[28px] border border-[#e6d9d7] bg-[#fffaf8] px-5 py-8 text-center sm:px-9 sm:py-10"><h2 className="text-3xl font-semibold tracking-tight text-neutral-950">Redo att se din känslighetsprofil?</h2><p className="mx-auto mt-3 max-w-xl leading-7 text-neutral-700">Svara på 30 frågor och få ett första resultat direkt i webbläsaren.</p><div className="mt-6"><Link data-rv="button" href="/hsp-test/test" className={cta}>Starta HSP-testet</Link></div><p className="mt-3 text-sm font-semibold text-neutral-700">30 frågor · resultat direkt</p></section>
    </article>
  </main></EditorialSurface>;
}
