import type { Metadata } from "next";
import Link from "next/link";
import { canonicalHost, findBehavior } from "../../content/behaviors";
import { ContentGuide, GuideLinks, GuideSection, SourceList, SupportNotice, textLink } from "../_components/ContentGuide";

export const metadata: Metadata = {
  title: "Digitalt våld i relation – kontroll, övervakning och hjälp",
  description: "Läs om digitalt våld: mobilkontroll, lösenord, meddelanden, platsdelning och krav på tillgänglighet. Förstå gränser och planera trygga nästa steg.",
  alternates: { canonical: `${canonicalHost}/digitalt-vald` },
};

const children = ["partner-kontrollerar-min-mobil", "partner-kraver-mitt-losenord", "partner-laser-mina-meddelanden", "partner-vill-veta-var-jag-ar"];

export default function DigitalViolenceGuide() {
  return <ContentGuide title="Digitalt våld i relation – kontroll, övervakning och vanliga tecken" intro="Digitalt våld är ett sätt att beskriva hur teknik kan användas för att kontrollera, hota eller kränka någon. I en relation kan det handla om mobilen, konton eller krav på att ständigt vara nåbar. Tekniken är en del av sammanhanget; frågan är vilket utrymme du får behålla." breadcrumbs={[{ href: "/beteenden", label: "Beteenden" }]}>
    <GuideSection title="Kontroll som följer med i fickan"><p>En partner behöver inte vara i samma rum för att ställa krav på dig. Meddelanden, platsuppgifter och kontotillgång kan förlänga en kontroll som också finns hemma. Men delad teknik är inte i sig våld: samtycke, möjlighet att ändra sig och reaktionerna på ett nej är viktiga skillnader.</p><p>Du behöver inte bevisa hur en teknisk lösning fungerar för att berätta att du känner dig övervakad. Börja med det du märker: vilka uppgifter partnern känner till, vilka krav som ställs och hur det påverkar din vardag.</p></GuideSection>
    <GuideSection title="Vanliga former av digital kontroll"><h3 className="text-xl font-semibold text-neutral-900">Telefon och meddelanden</h3><p>Det kan vara krav på att lämna ifrån sig mobilen, visa hela chattar eller redovisa kontakter. Ibland blir läsningen ett villkor för att partnern ska tro på dig. Andras förtroenden kan också bli synliga när dina privata samtal granskas.</p><h3 className="text-xl font-semibold text-neutral-900">Platsdelning och ständig tillgänglighet</h3><p>Att meddela en försening kan vara praktiskt. Att behöva vara spårbar hela tiden eller skicka bilder för att bevisa var du är kan bli begränsande. Upprepade samtal kan fylla samma funktion som teknik för positionering.</p><h3 className="text-xl font-semibold text-neutral-900">Sociala medier</h3><p>Partnern kan vilja godkänna bilder, bestämma vilka du får följa eller kräva att kontakter tas bort. Du kanske undviker att publicera något för att slippa förklara vilka som reagerat på det. Frågan är inte vilken app ni använder, utan om du kan fatta egna beslut.</p><h3 className="text-xl font-semibold text-neutral-900">Konton och enheter</h3><p>Den som har tillgång till e-post, återställningsuppgifter eller en redan inloggad enhet kan få mer insyn än du tänkt. Delade familjekonton och abonnemang kan också göra det oklart vem som kan se eller ändra vad. En notis eller ett tekniskt fel bevisar dock inte att någon övervakar dig.</p></GuideSection>
    <GuideSection title="Läs om den situation du känner igen"><GuideLinks links={children.map((slug) => ({ href: `/beteenden/${slug}`, label: findBehavior(slug)!.h1 }))} /></GuideSection>
    <GuideSection title="Frivillig öppenhet eller ett krav?"><p>En överenskommelse behöver kunna omprövas. Att du en gång visade ett meddelande betyder inte att du har sagt ja till framtida granskning av alla samtal. Inte heller behöver båda dela samma mängd privat information för att vara lojala.</p><ul className="list-disc space-y-3 pl-5"><li><strong>Platsdelning:</strong> ni väljer den för en resa och kan stänga av den, eller du måste alltid vara synlig för att undvika anklagelser.</li><li><strong>Telefonen:</strong> du lånar ut den för ett ärende, eller partnern behåller den för att kontrollera vem du pratar med.</li><li><strong>Kontakt:</strong> ni berättar när ni kan höras, eller ett försenat svar leder till press och förhör.</li></ul><p>En gemensam regel blir inte frivillig bara för att du till slut går med på den. Om alternativet känns skrämmande är det viktigt att kunna prata med någon utanför relationen.</p></GuideSection>
    <GuideSection title="Planera digitala förändringar med hänsyn till säkerheten"><p>Det finns ingen inställning som löser alla former av kontroll. Att byta lösenord, logga ut enheter eller stänga av platsdelning kan vara relevant, men förändringen kan märkas. Om du är rädd för partnerns reaktion, ta stöd innan du gör en större genomgång.</p><ol className="list-decimal space-y-3 pl-5"><li>Sök om möjligt stöd via en enhet och ett konto partnern inte har tillgång till. Privat webbläsarläge är inte ett fullständigt skydd mot övervakning.</li><li>Gör en överblick över vilka konton och enheter ni delar. Ta hjälp av tjänstens officiella support om du inte vet hur åtkomsten fungerar.</li><li>Planera hur du kan behålla en trygg kontaktväg under förändringar. Gör inte konfrontation eller teknisk bevisning till ett krav för att få hjälp.</li></ol></GuideSection>
    <SupportNotice />
    <GuideSection title="När kontrollen också finns utanför skärmen"><p>Digitala krav kan hänga ihop med <Link href="/kontrollerande-relation" className={textLink}>kontrollerande beteenden i vardagen</Link>. Guiden om <Link href="/psykiskt-vald" className={textLink}>psykiskt våld</Link> ger ett bredare sammanhang. Hur en enskild handling ska bedömas juridiskt behöver utredas utifrån omständigheterna.</p><p>För fler konkreta situationer kan du återvända till <Link href="/beteenden" className={textLink}>översikten över beteenden i relationer</Link>.</p></GuideSection>
    <SourceList ids={["digital", "violence"]} />
  </ContentGuide>;
}
