import type { Metadata } from "next";
import Link from "next/link";
import HealthyRelationshipTest from "./HealthyRelationshipTest";

export const metadata: Metadata = {
  title: "Är min relation sund? Gör relationstestet | Relationsvarning",
  description: "Svara på 12 frågor om trygghet, respekt, kommunikation och frihet i relationen. Se vilka områden som fungerar bra och vilka som kan behöva mer uppmärksamhet.",
  alternates: { canonical: "https://www.relationsvarning.se/ar-min-relation-sund" },
  openGraph: { title: "Är min relation sund? Gör relationstestet", description: "En kostnadsfri självskattning om styrkor och utvecklingsområden i relationen.", url: "https://www.relationsvarning.se/ar-min-relation-sund", type: "website" },
};

const breadcrumbJsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [
  { "@type": "ListItem", position: 1, name: "Relationsvarning", item: "https://www.relationsvarning.se/" },
  { "@type": "ListItem", position: 2, name: "Är min relation sund?", item: "https://www.relationsvarning.se/ar-min-relation-sund" },
] };

export default function HealthyRelationshipPage() {
  return <main className="bg-neutral-50 text-neutral-900"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd).replace(/</g, "\\u003c") }} /><article className="mx-auto max-w-3xl px-5 py-10 sm:px-6 sm:py-14"><nav aria-label="Brödsmulor" className="mb-7 text-sm text-neutral-500"><Link href="/" className="underline underline-offset-4">Start</Link><span aria-hidden="true"> / </span><span aria-current="page">Är min relation sund?</span></nav><header><p className="text-sm font-semibold uppercase tracking-[0.16em] text-neutral-500">Gratis relationstest · 12 frågor · cirka 2 minuter</p><h1 className="mt-3 text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">Är min relation sund?</h1><p className="mt-5 text-lg leading-8 text-neutral-700">En bra relation behöver inte vara konfliktfri. Det viktiga är ofta hur ni behandlar varandra när ni tycker olika, om båda får plats och om relationen ger mer trygghet än oro över tid.</p><p className="mt-4 leading-7 text-neutral-700">Det här kostnadsfria relationstestet hjälper dig att se både styrkor och områden som kan behöva mer uppmärksamhet. Du får hela resultatet direkt utan registrering eller betalning.</p></header>
    <section className="mt-9 rounded-2xl border border-neutral-200 bg-white p-5 sm:p-7"><h2 className="text-2xl font-semibold">Vad kännetecknar en sund relation?</h2><p className="mt-3 leading-7 text-neutral-700">I en sund relation finns utrymme för trygghet, respekt, kommunikation, självständighet och ömsesidighet. Båda kan uttrycka behov och gränser, behålla viktiga relationer utanför förhållandet och ta ansvar när något blivit fel.</p><p className="mt-3 leading-7 text-neutral-700">Olika perioder kan vara mer eller mindre stabila. Testet bedömer därför inte om relationen är perfekt. Det jämför sex områden som tillsammans kan ge en mer nyanserad bild av vad som fungerar och vad som kan vara värt att prata mer om.</p></section>
    <HealthyRelationshipTest />
    <section className="mt-12 space-y-8 border-t border-neutral-200 pt-10"><div><h2 className="text-2xl font-semibold">Så fungerar resultatet</h2><p className="mt-3 leading-7 text-neutral-700">Varje område bygger på två frågor och får mellan noll och sex poäng. Fem eller sex poäng visas som en tydlig styrka, tre eller fyra som ett mellanområde och noll till två som ett område som kan förtjäna mer uppmärksamhet.</p><p className="mt-3 leading-7 text-neutral-700">Sammanfattningen bygger på hur många områden som hamnar på respektive nivå. Den försöker inte hitta ett problem när svaren är positiva och använder inte totalsumman som en ensam etikett på relationen.</p></div><div><h2 className="text-2xl font-semibold">Vanliga frågor</h2><div className="mt-5 space-y-6"><div><h3 className="font-semibold">Kan ett test avgöra om min relation är bra?</h3><p className="mt-2 leading-7 text-neutral-700">Nej. Testet kan strukturera din egen upplevelse, men relationer påverkas av sammanhang som inte ryms i tolv frågor. Se resultatet som underlag för reflektion och samtal.</p></div><div><h3 className="font-semibold">Kan en sund relation innehålla konflikter?</h3><p className="mt-2 leading-7 text-neutral-700">Ja. Skillnaden ligger ofta i om båda kan återvända till samtalet, ta ansvar och reparera utan rädsla, förlöjligande eller bestraffning. Konflikt i sig betyder inte att relationen är osund.</p></div><div><h3 className="font-semibold">Vad gör jag om ett område får låg poäng?</h3><p className="mt-2 leading-7 text-neutral-700">Titta på de konkreta frågorna och fundera på om mönstret är tillfälligt eller återkommande. Resultatet visar relevanta guider eller tester endast när en dimension faktiskt ligger på den svagare nivån.</p></div><div><h3 className="font-semibold">Hur skiljer sig detta från testet om röda flaggor?</h3><p className="mt-2 leading-7 text-neutral-700">Det här testet utgår från positiva relationskvaliteter och visar styrkor såväl som utvecklingsområden. <Link href="/roda-flaggor-relation-test" className="font-medium underline underline-offset-4">Snabbchecken om röda flaggor</Link> fokuserar i stället på återkommande varningssignaler och problematiska beteenden.</p></div><div><h3 className="font-semibold">Sparas mina svar?</h3><p className="mt-2 leading-7 text-neutral-700">Svaren sparas lokalt i din webbläsare för att testet ska tåla en uppdatering. Individuella svar, frågor och råa poäng skickas inte till analytics.</p></div></div></div></section>
  </article></main>;
}
